import type { Recipe } from "./types";

type BookRecipe = Omit<Recipe, "missing" | "servings"> & {
  tags: string[];
  baseServings: number;
};

export const RECIPES_BASE: BookRecipe[] = [
  {
    id: "pesto",
    title: "Pasta al pesto cremosa",
    description:
      "Il pesto genovese diventa una salsa setosa quando viene allungato con l'acqua di cottura amilacea: il basilico resta vivo, il formaggio si fonde senza grumi e la pasta esce lucida e profumata. Un piatto che sa di Liguria ma si cucina in venti minuti con quello che hai già in frigo.",
    minutes: 20,
    diet: "vegetarian",
    tags: ["pasta", "pesto", "parmigiano", "basilico"],
    ingredients: [
      "320 g di pasta corta (trofie, penne o fusilli)",
      "3–4 cucchiai di pesto genovese",
      "40 g di parmigiano grattugiato",
      "1 cucchiaio di olio extravergine",
      "sale grosso per l'acqua",
    ],
    steps: [
      "Porta a bollore una pentola abbondante d'acqua, sala generosamente e tuffa la pasta. Cuocila 1 minuto in meno rispetto al tempo indicato sulla confezione: finirà di cuocere in padella.",
      "In una ciotola larga stempera il pesto con l'olio e 2–3 cucchiai di acqua di cottura calda. Devi ottenere una salsa fluida, brillante e non pastosa.",
      "Scola la pasta tenendo da parte un mestolo d'acqua. Trasferiscila subito nella ciotola e manteca energicamente per farla assorbire.",
      "Aggiungi il parmigiano e, se serve, ancora un filo d'acqua: la salsa deve avvolgere ogni pezzo senza restare sul fondo.",
      "Assaggia, regola di sale e servi immediatamente. Non far bollire il pesto: il calore residuo della pasta è sufficiente.",
    ],
    tip: "Se il pesto è molto denso o freddo di frigo, allungalo solo con acqua di cottura: l'amido lega meglio dell'olio da solo e mantiene il colore verde brillante.",
    art: "/graphics/avocado.jpg",
    baseServings: 2,
  },
  {
    id: "caprese",
    title: "Caprese al pomodoro maturo",
    description:
      "Pochi ingredienti di qualità fanno un piatto che sa d'estate: mozzarella fredda e compatta, pomodori sodi e dolci, olio intenso e basilico spezzettato a mano. Ideale come antipasto fresco o pranzo leggero quando non hai voglia di accendere i fornelli.",
    minutes: 10,
    diet: "vegetarian",
    tags: ["mozzarella", "pomodori", "basilico", "olio"],
    ingredients: [
      "250 g di mozzarella (o fior di latte)",
      "2–3 pomodori maturi ma sodi",
      "2 cucchiai di olio extravergine",
      "sale fino e pepe nero",
      "qualche foglia di basilico (se ce l'hai)",
    ],
    steps: [
      "Scola bene la mozzarella e lasciala 5 minuti su carta assorbente: così non allaga il piatto con l'acqua di governo.",
      "Affetta mozzarella e pomodori a dischi spessi circa 1 cm, scartando i pezzi troppo acquosi o verdi.",
      "Alterna i dischi sul piatto leggermente sovrapposti. Sali e pepa con mano leggera, solo al momento.",
      "Condisci con l'olio a filo e, se presente, il basilico spezzettato a mano (non tagliato col coltello, perde meno aroma).",
      "Lascia riposare 2–3 minuti a temperatura ambiente e servi fresco, non di frigo: i sapori si aprono.",
    ],
    tip: "Sala i pomodori solo un attimo prima di servire: se li sali troppo presto rilasciano acqua e diluiscono l'olio.",
    art: "/graphics/tomato.jpg",
    baseServings: 2,
  },
  {
    id: "frittata",
    title: "Frittata alta di zucchine",
    description:
      "Frittata dorata fuori e soffice dentro, con zucchine rosate e parmigiano. Si cuoce lentamente in padella, si gira con un piatto e resta umida al centro. Perfetta tiepida, fredda o da asporto: un classico della cucina casalinga italiana.",
    minutes: 25,
    diet: "vegetarian",
    tags: ["uova", "zucchine", "parmigiano", "cipolla"],
    ingredients: [
      "4 uova medie",
      "2 zucchine medie",
      "1/2 cipolla",
      "40 g di parmigiano grattugiato",
      "2 cucchiai di olio extravergine",
      "sale e pepe",
    ],
    steps: [
      "Taglia la cipolla a fettine sottili e le zucchine a rondelle. Scalda l'olio in una padella antiaderente da 22–24 cm.",
      "Rosola la cipolla 2 minuti, poi aggiungi le zucchine. Cuoci 8–10 minuti a fuoco medio fino a tenere e leggermente dorate. Sali a metà cottura.",
      "In una ciotola sbatti le uova con parmigiano, un pizzico di sale e pepe abbondante.",
      "Distribuisci le verdure, versa le uova e livella. Cuoci coperto a fuoco basso 6–7 minuti, finché i bordi sono presi.",
      "Con un piatto gira la frittata e cuoci altri 3–4 minuti, oppure finisci 2 minuti sotto il grill.",
      "Lascia intiepidire 5 minuti prima di tagliare: si assesta e resta più umida al centro.",
    ],
    tip: "Fuoco basso e padella antiaderente evitano il fondo bruciato e un cuore ancora liquido.",
    art: "/graphics/onion.jpg",
    baseServings: 2,
  },
  {
    id: "insalata",
    title: "Insalata croccante al limone",
    description:
      "Insalata fresca e acidula, con carote croccanti e un condimento al limone che sveglia il palato in pochi minuti. Ideale come contorno o pranzo leggero.",
    minutes: 8,
    diet: "vegan",
    tags: ["insalata", "limone", "olio", "carote"],
    ingredients: [
      "1 cespo di insalata (lattuga, iceberg o misticanza)",
      "1 carota media",
      "succo di 1/2 limone",
      "2 cucchiai di olio extravergine",
      "sale fino",
    ],
    steps: [
      "Lava l'insalata in acqua fredda e asciugala bene: l'acqua residua diluisce il condimento.",
      "Sbuccia la carota e tagliala a julienne fine o grattugiala a fori larghi.",
      "In una ciotola emulsiona limone, olio e un pizzico di sale con una forchetta.",
      "Unisci insalata e carote, condisci e mescola delicatamente.",
      "Assaggia e servi subito per mantenere il croccante.",
    ],
    tip: "Condici solo al momento di portare in tavola, altrimenti l'insalata si affloscia.",
    art: "/graphics/lettuce.jpg",
    baseServings: 2,
  },
  {
    id: "pomodoro",
    title: "Pasta al pomodoro semplice",
    description:
      "Sugo corto, dolce e lucido: cipolla soffritta, pomodori e pasta mantecata in padella. Comfort food italiano che trasforma i pomodori del frigo in un piatto completo.",
    minutes: 25,
    diet: "vegan",
    tags: ["pasta", "pomodori", "cipolla", "olio"],
    ingredients: [
      "320 g di pasta",
      "400 g di pomodori maturi (o pelati)",
      "1 cipolla piccola",
      "2 cucchiai di olio extravergine",
      "sale e pepe",
      "basilico fresco (opzionale)",
    ],
    steps: [
      "Trita la cipolla e soffriggila nell'olio a fuoco medio-basso 4–5 minuti, senza bruciarla.",
      "Aggiungi i pomodori spezzettati, sala e lascia sobbollire 12–15 minuti finché il sugo si restringe e diventa lucido.",
      "Cuoci la pasta in acqua salata e scolala molto al dente (1–2 minuti prima).",
      "Trasferisci la pasta nel sugo con un mestolo d'acqua di cottura e manteca 1–2 minuti a fuoco vivo.",
      "Spegni, aggiungi pepe e basilico se ce l'hai. Servi subito.",
    ],
    tip: "Un pizzico di zucchero serve solo se i pomodori sono acidi: assaggia prima.",
    art: "/graphics/tomato.jpg",
    baseServings: 2,
  },
  {
    id: "funghi",
    title: "Funghi saltati all'aglio",
    description:
      "Funghi rosati a fiamma viva, aglio e prezzemolo: contorno saporito o base per crostini e pasta. Un modo veloce per dare carattere ai funghi del frigo.",
    minutes: 15,
    diet: "vegan",
    tags: ["funghi", "aglio", "prezzemolo", "olio"],
    ingredients: [
      "400 g di funghi champignon (o misti)",
      "1 spicchio d'aglio",
      "2 cucchiai di olio extravergine",
      "prezzemolo tritato",
      "sale e pepe",
    ],
    steps: [
      "Pulisci i funghi con un panno umido, senza immergerli. Tagliali a fette regolari.",
      "Scalda bene la padella con l'olio. Aggiungi l'aglio schiacciato 30 secondi senza bruciarlo.",
      "Tuffa i funghi e non mescolare per 1–2 minuti: devono rosolare e perdere l'acqua.",
      "Quando l'acqua è evaporata, mescola e cuoci ancora 4–5 minuti a fuoco medio-alto.",
      "Sali, pepa, togli l'aglio se preferisci e completa con prezzemolo. Servi caldi.",
    ],
    tip: "Padella spaziosa e fuoco alto: se li sovrapponi, i funghi lessano invece di saltare.",
    art: "/graphics/mushrooms.jpg",
    baseServings: 2,
  },
  {
    id: "peperoni",
    title: "Peperoni stufati in padella",
    description:
      "Peperoni dolci e cipolla cotti lentamente fino a diventare morbidi e caramellati. Ottimi anche il giorno dopo, come contorno o su bruschette.",
    minutes: 25,
    diet: "vegan",
    tags: ["peperoni", "cipolla", "olio"],
    ingredients: [
      "3 peperoni (rossi o misti)",
      "1 cipolla",
      "2 cucchiai di olio extravergine",
      "sale",
      "origano o pepe (opzionale)",
    ],
    steps: [
      "Mondate i peperoni: togli picciolo, semi e filamenti. Tagliali a strisce non troppo sottili.",
      "Affetta la cipolla e mettila in padella con l'olio. Quando traspare, unisci i peperoni.",
      "Sala, copri e cuoci 15 minuti mescolando ogni tanto.",
      "Scopri e alza il fuoco 5 minuti per far restringere i succhi.",
      "Regola di sale e servi caldi, tiepidi o freddi.",
    ],
    tip: "Un cucchiaio d'aceto o un goccio di limone a fine cottura bilancia la dolcezza.",
    art: "/graphics/pepper.jpg",
    baseServings: 2,
  },
  {
    id: "uova-strapazzate",
    title: "Uova cremose al parmigiano",
    description:
      "Uova strapazzate lente e cremose, arricchite di parmigiano e un filo di latte. Colazione o cena lampo quando in frigo ci sono solo uova e formaggio.",
    minutes: 8,
    diet: "vegetarian",
    tags: ["uova", "parmigiano", "latte"],
    ingredients: [
      "3 uova",
      "2 cucchiai di latte",
      "30 g di parmigiano grattugiato",
      "un noce di burro (o 1 cucchiaio d'olio)",
      "sale e pepe",
    ],
    steps: [
      "Sbatti uova, latte, parmigiano, sale e pepe fino a un composto omogeneo.",
      "Scalda una padella antiaderente a fuoco basso con il burro: deve fondere senza sfrigolare forte.",
      "Versa le uova e mescola in continuazione con una spatola, dal bordo verso il centro.",
      "Quando sono ancora lucide e cremose, spegni: finiscono di cuocere col calore residuo.",
      "Servi subito su pane tostato o da sole.",
    ],
    tip: "Il segreto è il fuoco bassissimo: a fiamma alta diventano secche in pochi secondi.",
    art: "/graphics/lemon.jpg",
    baseServings: 1,
  },
  {
    id: "pasta-limone",
    title: "Pasta al limone e parmigiano",
    description:
      "Salsa al limone setosa, burro e parmigiano: piatto luminoso e veloce quando in frigo c'è solo un agrume. Acidità e cremosità in perfetto equilibrio.",
    minutes: 18,
    diet: "vegetarian",
    tags: ["pasta", "limone", "parmigiano", "burro"],
    ingredients: [
      "320 g di pasta lunga o corta",
      "1 limone non trattato (scorza e succo)",
      "40 g di burro",
      "50 g di parmigiano grattugiato",
      "sale e pepe nero",
    ],
    steps: [
      "Metti a bollire l'acqua. Grattugia la scorza del limone e spremine metà, filtrando i semi.",
      "In una padella sciogli il burro a fuoco basso con la scorza, senza far colorire.",
      "Cuoci la pasta e scolala al dente, tenendo da parte un mestolo d'acqua di cottura.",
      "Trasferisci la pasta in padella con succo di limone, un po' d'acqua e il parmigiano. Manteca energicamente.",
      "Regola la densità con altra acqua: la salsa deve avvolgere la pasta. Pepa e servi subito.",
    ],
    tip: "Se la salsa si spezza, togli dal fuoco e manteca con un cucchiaio d'acqua fredda.",
    art: "/graphics/lemon.jpg",
    baseServings: 2,
  },
  {
    id: "carote-yogurt",
    title: "Insalata di carote allo yogurt",
    description:
      "Carote grattugiate in una salsa allo yogurt e limone: contorno fresco, leggero e pronto in pochi minuti. Ideale per bilanciare piatti più ricchi.",
    minutes: 12,
    diet: "vegetarian",
    tags: ["carote", "yogurt", "limone"],
    ingredients: [
      "3 carote medie",
      "150 g di yogurt bianco",
      "succo di 1/2 limone",
      "1 cucchiaio di olio extravergine",
      "sale e pepe",
    ],
    steps: [
      "Sbuccia le carote e grattugiale a fori medi.",
      "Mescola yogurt, limone, olio, sale e pepe fino a una salsa cremosa ma fluida.",
      "Unisci le carote e amalgama bene.",
      "Lascia riposare 5 minuti in frigo: i sapori si bilanciano.",
      "Assaggia, regola di limone o sale e servi fresco.",
    ],
    tip: "Con yogurt greco denso, allunga con un cucchiaio d'acqua per non avere un composto pastoso.",
    art: "/graphics/lettuce.jpg",
    baseServings: 2,
  },
  {
    id: "zucchine",
    title: "Zucchine trifolate in padella",
    description:
      "Zucchine saltate con aglio e olio, tenere fuori e ancora con morso. Contorno veloce o condimento per pasta: un classico della cucina di casa.",
    minutes: 15,
    diet: "vegan",
    tags: ["zucchine", "aglio", "olio"],
    ingredients: [
      "3 zucchine medie",
      "1 spicchio d'aglio",
      "2 cucchiai di olio extravergine",
      "sale e pepe",
      "prezzemolo (opzionale)",
    ],
    steps: [
      "Taglia le zucchine a rondelle di 4–5 mm o a bastoncini.",
      "Scalda l'olio con l'aglio schiacciato. Quando profuma, togli l'aglio se preferisci un gusto delicato.",
      "Aggiungi le zucchine e fallole saltare 8–10 minuti a fuoco medio-alto.",
      "Sala a metà cottura: così non rilasciano troppa acqua subito.",
      "Pepa, completa con prezzemolo se ce l'hai e servi.",
    ],
    tip: "Non coprire la padella: il vapore le rende mollicce invece che rosate.",
    art: "/graphics/onion.jpg",
    baseServings: 2,
  },
  {
    id: "mozza-pesto",
    title: "Mozzarella tiepida al pesto",
    description:
      "Antipasto lampo: mozzarella scolata, un velo di pesto e olio a crudo. Ideale con pane croccante quando hai poco tempo e vuoi qualcosa di buono.",
    minutes: 6,
    diet: "vegetarian",
    tags: ["mozzarella", "pesto", "olio"],
    ingredients: [
      "200 g di mozzarella",
      "2 cucchiai di pesto",
      "1 cucchiaio di olio extravergine",
      "pepe nero",
      "pane tostato per servire",
    ],
    steps: [
      "Scola e asciuga la mozzarella. Tagliala a fette spesse o a cubetti grossi.",
      "Disponila sul piatto e spalma un velo sottile di pesto su ogni pezzo.",
      "Completa con un filo d'olio e una macinata di pepe.",
      "Servi subito con pane tostato o crostini caldi.",
    ],
    tip: "Se la mozzarella è di frigo, lasciala 10 minuti a temperatura ambiente: il sapore si apre.",
    art: "/graphics/avocado.jpg",
    baseServings: 1,
  },
  {
    id: "uova-pomodoro",
    title: "Uova in purgatorio",
    description:
      "Uova poaché in un sugo di pomodoro speziato e leggero: piatto unico saporito che usa uova e pomodori del frigo. Perfetto per una cena veloce e confortante.",
    minutes: 20,
    diet: "vegetarian",
    tags: ["uova", "pomodori", "cipolla", "aglio"],
    ingredients: [
      "4 uova",
      "400 g di pomodori maturi (o pelati)",
      "1 spicchio d'aglio",
      "1/2 cipolla",
      "2 cucchiai di olio extravergine",
      "sale, pepe e un pizzico di peperoncino (opzionale)",
    ],
    steps: [
      "Trita cipolla e aglio. Soffriggili nell'olio a fuoco medio 3–4 minuti.",
      "Aggiungi i pomodori spezzettati, sala e lascia sobbollire 10 minuti fino a un sugo denso ma ancora fluido.",
      "Con un cucchiaio forma quattro nicchie nel sugo e rompi le uova dentro.",
      "Copri e cuoci a fuoco basso 4–6 minuti: il bianco deve coagulare, il tuorlo restare morbido.",
      "Pepa, completa con un filo d'olio e servi con pane tostato.",
    ],
    tip: "Non alzare troppo il fuoco: le uova devono cuocere piano nel sugo, non friggere.",
    art: "/graphics/tomato.jpg",
    baseServings: 2,
  },
  {
    id: "pasta-zucchine",
    title: "Pasta alle zucchine e parmigiano",
    description:
      "Pasta mantecata con zucchine dorate e parmigiano: piatto cremoso senza panna, leggero e pieno di sapore. Ideale quando le zucchine iniziano ad accumularsi in frigo.",
    minutes: 22,
    diet: "vegetarian",
    tags: ["pasta", "zucchine", "parmigiano", "aglio"],
    ingredients: [
      "320 g di pasta",
      "3 zucchine medie",
      "40 g di parmigiano grattugiato",
      "1 spicchio d'aglio",
      "2 cucchiai di olio extravergine",
      "sale e pepe",
    ],
    steps: [
      "Taglia le zucchine a rondelle sottili. Scalda l'olio con l'aglio, poi unisci le zucchine.",
      "Cuoci 10–12 minuti a fuoco medio-alto fino a dorate e tenere. Sali a metà cottura.",
      "Cuoci la pasta al dente e scolala tenendo da parte un mestolo d'acqua.",
      "Trasferisci la pasta nella padella delle zucchine, aggiungi parmigiano e un po' d'acqua di cottura.",
      "Manteca a fuoco vivo 1 minuto: la salsa deve legare. Pepa e servi subito.",
    ],
    tip: "Se vuoi più cremosità, aggiungi un cucchiaio di acqua di cottura in più mentre mantechi: l'amido fa miracoli.",
    art: "/graphics/onion.jpg",
    baseServings: 2,
  },
  {
    id: "insalata-mozza",
    title: "Insalata di mozzarella e pomodori",
    description:
      "Versione più ricca della caprese: insalata di base croccante, pomodori a spicchi, mozzarella a cubetti e un condimento semplice all'olio e limone. Piatto completo, fresco e bilanciato, pronto in dieci minuti.",
    minutes: 10,
    diet: "vegetarian",
    tags: ["insalata", "mozzarella", "pomodori", "limone"],
    ingredients: [
      "1 cespo di insalata",
      "200 g di mozzarella",
      "2 pomodori maturi",
      "succo di 1/2 limone",
      "2 cucchiai di olio extravergine",
      "sale e pepe",
    ],
    steps: [
      "Lava e asciuga l'insalata, poi spezzettala a pezzi grossolani. Scola e taglia la mozzarella a cubetti.",
      "Taglia i pomodori a spicchi o a cubetti medi, scartando l'acqua in eccesso.",
      "In una ciotola grande unisci insalata, mozzarella e pomodori.",
      "Condisci con limone, olio, sale e pepe. Mescola delicatamente.",
      "Servi subito, eventualmente con pane tostato a parte.",
    ],
    tip: "Se prepari in anticipo, tieni il condimento a parte e unisci tutto solo al momento di servire.",
    art: "/graphics/lettuce.jpg",
    baseServings: 2,
  },
];
