import type { Recipe } from "./types";

type BookRecipe = Omit<Recipe, "missing" | "servings"> & {
  tags: string[];
  baseServings: number;
};

export const RECIPES_PASTA: BookRecipe[] = [
  {
    id: "aglio-olio",
    title: "Spaghetti aglio, olio e peperoncino",
    description:
      "Il piatto della dispensa per eccellenza: aglio dorato, olio fruttato e un pizzico di peperoncino. Semplice, profumato e pronto in meno di un quarto d'ora. Perfetto quando il frigo è quasi vuoto ma vuoi comunque qualcosa di buono.",
    minutes: 15,
    diet: "vegan",
    tags: ["pasta", "aglio", "olio", "peperoncino"],
    ingredients: [
      "320 g di spaghetti",
      "3 spicchi d'aglio",
      "4 cucchiai di olio extravergine",
      "1 peperoncino fresco o secco",
      "sale grosso",
      "prezzemolo (opzionale)",
    ],
    steps: [
      "Metti a bollire l'acqua e sala. Nel frattempo affetta l'aglio a fettine sottili e sminuzza il peperoncino.",
      "In una padella larga scalda l'olio a fuoco medio-basso con aglio e peperoncino: devono dorare senza bruciare (3–4 minuti).",
      "Cuoci gli spaghetti al dente e scolali tenendo da parte un mestolo d'acqua di cottura.",
      "Trasferisci la pasta in padella, aggiungi un filo d'acqua e manteca 1 minuto a fuoco vivo.",
      "Spegni, completa con prezzemolo se ce l'hai e servi subito.",
    ],
    tip: "Se l'aglio inizia a scurirsi troppo, spegni e continua a mescolare fuori dal fuoco: il calore residuo basta.",
    art: "/graphics/onion.jpg",
    baseServings: 2,
  },
  {
    id: "cacio-pepe",
    title: "Cacio e pepe",
    description:
      "Pochi ingredienti, tecnica precisa: pecorino (o parmigiano), pepe tostato e amido dell'acqua di cottura creano una crema vellutata che avvolge la pasta. Un classico romano che si può fare anche in casa con quello che c'è.",
    minutes: 20,
    diet: "vegetarian",
    tags: ["pasta", "parmigiano", "pepe"],
    ingredients: [
      "320 g di tonnarelli o spaghetti",
      "120 g di pecorino romano (o parmigiano grattugiato)",
      "pepe nero macinato fresco",
      "sale grosso",
    ],
    steps: [
      "Tosta il pepe in padella a secco 1 minuto, poi pestalo grossolanamente. Metti a bollore poca acqua (serve concentrata).",
      "Cuoci la pasta in acqua poco salata. Nel frattempo mescola il formaggio con un mestolo d'acqua di cottura calda fino a una crema densa.",
      "Scola la pasta al dente tenendo da parte l'acqua. Trasferiscila in una ciotola con il pepe.",
      "Aggiungi la crema di formaggio e manteca energicamente, aggiungendo acqua poco alla volta.",
      "La salsa deve essere lucida e avvolgente. Servi subito con altra grattugiata di formaggio e pepe.",
    ],
    tip: "Niente panico se si gruma: togli dal fuoco e aggiungi un cucchiaio d'acqua fredda mescolando con vigore.",
    art: "/graphics/lemon.jpg",
    baseServings: 2,
  },
  {
    id: "pasta-tonno",
    title: "Pasta al tonno e limone",
    description:
      "Tonno sott'olio, scorza di limone e un filo d'aglio: piatto di mare veloce, saporito e bilanciato. Ideale quando hai una scatoletta di tonno e un limone in frigo.",
    minutes: 18,
    diet: "omnivore",
    tags: ["pasta", "tonno", "limone", "aglio"],
    ingredients: [
      "320 g di pasta corta o lunga",
      "1 scatoletta di tonno sott'olio (160 g sgocciolato)",
      "1 limone (scorza e un filo di succo)",
      "1 spicchio d'aglio",
      "2 cucchiai di olio extravergine",
      "prezzemolo e pepe",
    ],
    steps: [
      "Metti a bollire l'acqua. In padella scalda l'olio con l'aglio schiacciato 1 minuto.",
      "Aggiungi il tonno sbriciolato e la scorza di limone. Cuoci 2 minuti a fuoco medio.",
      "Cuoci la pasta al dente e scolala tenendo da parte un po' d'acqua.",
      "Unisci pasta e tonno, manteca con un filo d'acqua e un goccio di succo di limone.",
      "Completa con prezzemolo e pepe. Servi subito.",
    ],
    tip: "Non scolare troppo il tonno: un po' del suo olio dà sapore e lega meglio.",
    art: "/graphics/lemon.jpg",
    baseServings: 2,
  },
  {
    id: "pasta-ricotta",
    title: "Pasta alla ricotta e limone",
    description:
      "Ricotta stemperata con acqua di cottura, scorza di limone e parmigiano: crema bianca, fresca e leggera. Un piatto elegante che si prepara mentre la pasta bolle.",
    minutes: 18,
    diet: "vegetarian",
    tags: ["pasta", "ricotta", "limone", "parmigiano"],
    ingredients: [
      "320 g di pasta",
      "200 g di ricotta fresca",
      "1 limone non trattato (scorza)",
      "40 g di parmigiano grattugiato",
      "sale e pepe nero",
      "un filo d'olio",
    ],
    steps: [
      "Metti a bollire l'acqua. In una ciotola stempera la ricotta con un mestolo d'acqua calda, scorza di limone e parmigiano.",
      "Devi ottenere una crema liscia e fluida. Regola di sale e pepe.",
      "Cuoci la pasta al dente e scolala tenendo da parte acqua.",
      "Trasferisci la pasta nella ciotola e manteca energicamente, aggiungendo acqua se serve.",
      "Completa con un filo d'olio e altra scorza. Servi subito.",
    ],
    tip: "La ricotta deve essere a temperatura ambiente: se è di frigo, lasciala 10 minuti fuori prima di stemperarla.",
    art: "/graphics/lemon.jpg",
    baseServings: 2,
  },
  {
    id: "pasta-funghi",
    title: "Pasta ai funghi cremosa",
    description:
      "Funghi rosati, aglio e un filo di panna o acqua di cottura: sugo terroso e avvolgente che si lega alla pasta in pochi minuti. Ideale quando hai un vassoio di champignon in frigo.",
    minutes: 25,
    diet: "vegetarian",
    tags: ["pasta", "funghi", "aglio", "panna"],
    ingredients: [
      "320 g di pasta",
      "400 g di funghi champignon",
      "1 spicchio d'aglio",
      "100 ml di panna fresca (o latte + parmigiano)",
      "2 cucchiai di olio extravergine",
      "prezzemolo, sale e pepe",
    ],
    steps: [
      "Pulisci e affetta i funghi. Scalda l'olio con l'aglio, poi tuffa i funghi e falli rosolare a fuoco alto 6–7 minuti.",
      "Quando l'acqua è evaporata, aggiungi la panna, sala e lascia restringere 2 minuti.",
      "Cuoci la pasta al dente e scolala tenendo da parte acqua.",
      "Unisci pasta e funghi, manteca con un filo d'acqua se serve.",
      "Completa con prezzemolo e pepe. Servi caldo.",
    ],
    tip: "Padella grande e fuoco alto all'inizio: i funghi devono rosolare, non lessare.",
    art: "/graphics/mushrooms.jpg",
    baseServings: 2,
  },
  {
    id: "pasta-pomodorini",
    title: "Pasta ai pomodorini scottati",
    description:
      "Pomodorini fatti scoppiare in padella con aglio e basilico: sugo fresco, dolce e luminoso in meno di venti minuti. Il segreto è non cuocerli troppo a lungo.",
    minutes: 20,
    diet: "vegan",
    tags: ["pasta", "pomodori", "aglio", "basilico"],
    ingredients: [
      "320 g di pasta",
      "400 g di pomodorini",
      "2 spicchi d'aglio",
      "3 cucchiai di olio extravergine",
      "basilico fresco",
      "sale e pepe",
    ],
    steps: [
      "In padella larga scalda l'olio con l'aglio. Aggiungi i pomodorini interi o a metà.",
      "Cuoci a fuoco medio-alto 8–10 minuti, schiacciandoli leggermente finché rilasciano il succo.",
      "Sala e lascia restringere 2 minuti. Cuoci la pasta al dente.",
      "Scola la pasta e trasferiscila in padella con un filo d'acqua di cottura.",
      "Manteca 1 minuto, spegni e aggiungi basilico spezzettato. Servi.",
    ],
    tip: "Non coprire la padella: vuoi che i pomodorini si caramellino un po', non che si stufino.",
    art: "/graphics/tomato.jpg",
    baseServings: 2,
  },
  {
    id: "pasta-broccoli",
    title: "Pasta e broccoli",
    description:
      "Broccoli cotti fino a diventare cremosi, poi mantecati con pasta e un filo d'olio: piatto povero, sano e soddisfacente. Un classico del Sud che usa verdure e dispensa.",
    minutes: 25,
    diet: "vegan",
    tags: ["pasta", "broccoli", "aglio", "olio"],
    ingredients: [
      "320 g di pasta corta",
      "1 cespo di broccoli (circa 400 g)",
      "2 spicchi d'aglio",
      "3 cucchiai di olio extravergine",
      "sale e peperoncino",
    ],
    steps: [
      "Dividi i broccoli in cimette e cuocili nell'acqua della pasta per 8–10 minuti.",
      "In padella soffriggi aglio e peperoncino nell'olio. Aggiungi i broccoli scolati e schiacciali leggermente.",
      "Cuoci la pasta nello stesso acqua dei broccoli e scolala al dente.",
      "Unisci pasta e broccoli, manteca con un filo d'acqua di cottura.",
      "Regola di sale e servi con un filo d'olio a crudo.",
    ],
    tip: "L'acqua di cottura dei broccoli è ricca di sapore: usala per legare invece di scolarla via.",
    art: "/graphics/lettuce.jpg",
    baseServings: 2,
  },
  {
    id: "pasta-carbonara",
    title: "Carbonara classica",
    description:
      "Uova, pecorino, guanciale e pepe: la carbonara vera non usa panna. Una crema vellutata che si forma col calore della pasta. Piatto iconico romano, ricco e profondamente saporito.",
    minutes: 25,
    diet: "omnivore",
    tags: ["pasta", "uova", "guanciale", "pecorino"],
    ingredients: [
      "320 g di spaghetti o rigatoni",
      "150 g di guanciale (o pancetta)",
      "3 tuorli + 1 uovo intero",
      "80 g di pecorino romano grattugiato",
      "pepe nero abbondante",
    ],
    steps: [
      "Taglia il guanciale a listarelle e rosolalo in padella a fuoco medio finché diventa croccante e rilascia il grasso.",
      "In una ciotola sbatti tuorli, uovo intero, pecorino e pepe fino a una crema densa.",
      "Cuoci la pasta al dente in acqua poco salata. Scolala tenendo da parte acqua.",
      "Spegni il fuoco sotto il guanciale, aggiungi la pasta e un filo d'acqua. Mescola.",
      "Togli dal fuoco e unisci la crema di uova mescolando velocemente: deve legare senza fare frittata. Servi subito.",
    ],
    tip: "La temperatura è tutto: fuori dal fuoco e pasta ancora calda. Se serve, un cucchiaio d'acqua di cottura aiuta a stemperare.",
    art: "/graphics/onion.jpg",
    baseServings: 2,
  },
  {
    id: "pasta-salsiccia",
    title: "Pasta con salsiccia e pomodoro",
    description:
      "Salsiccia sbriciolata, pomodoro e un filo di vino: sugo ricco e confortante in mezz'ora. Ideale per una cena sostanziosa quando hai salsicce in frigo.",
    minutes: 30,
    diet: "omnivore",
    tags: ["pasta", "salsiccia", "pomodori", "cipolla"],
    ingredients: [
      "320 g di pasta corta",
      "300 g di salsiccia",
      "300 g di pomodori pelati o passata",
      "1/2 cipolla",
      "1 cucchiaio di olio",
      "sale e pepe",
    ],
    steps: [
      "Togli il budello alla salsiccia e sbriciolala. Soffriggi la cipolla nell'olio, poi aggiungi la salsiccia.",
      "Rosola 5–6 minuti a fuoco medio-alto. Aggiungi i pomodori, sala e lascia sobbollire 15 minuti.",
      "Cuoci la pasta al dente e scolala.",
      "Unisci pasta e sugo, manteca 1 minuto. Pepa e servi.",
    ],
    tip: "Un goccio di vino bianco dopo aver rosolato la salsiccia deglassia e aggiunge profondità.",
    art: "/graphics/tomato.jpg",
    baseServings: 2,
  },
  {
    id: "pasta-melanzane",
    title: "Pasta alla Norma veloce",
    description:
      "Melanzane dorate, pomodoro e ricotta salata (o parmigiano): versione casalinga e veloce della Norma. Dolcezza delle melanzane e acidità del pomodoro in equilibrio.",
    minutes: 30,
    diet: "vegetarian",
    tags: ["pasta", "melanzane", "pomodori", "ricotta"],
    ingredients: [
      "320 g di pasta corta",
      "2 melanzane medie",
      "300 g di pomodori pelati",
      "1 spicchio d'aglio",
      "olio per friggere e condire",
      "ricotta salata o parmigiano",
      "basilico",
    ],
    steps: [
      "Taglia le melanzane a cubetti, salale e lasciale 10 minuti. Asciugale e friggile in olio abbondante finché dorate.",
      "In un'altra padella soffriggi l'aglio, aggiungi i pomodori e cuoci 10 minuti.",
      "Cuoci la pasta al dente. Unisci sugo, melanzane e pasta, manteca.",
      "Completa con ricotta salata grattugiata e basilico. Servi.",
    ],
    tip: "Le melanzane devono essere ben dorate: se restano chiare assorbono olio e restano mollicce.",
    art: "/graphics/pepper.jpg",
    baseServings: 2,
  },
];
