import type { Recipe } from "./types";

type BookRecipe = Omit<Recipe, "missing" | "servings"> & {
  tags: string[];
  baseServings: number;
};

/** Primi e dessert standardizzati per il ricettario classico. */

export const RECIPES_PRIMI_DESSERT: BookRecipe[] = [

  {
    id: "carbonara-veloce",
    title: "Carbonara veloce",
    description:
      "Il primo romano per eccellenza, cremoso e saporito, pronto nel tempo di cottura della pasta.",
    minutes: 15,
    diet: "omnivore",
    tags: ["pasta", "guanciale", "uova", "pecorino"],
    ingredients: ["200 g di spaghetti", "100 g di guanciale o pancetta", "3 tuorli d'uovo", "40 g di pecorino romano o parmigiano", "pepe nero q.b."],
    steps: ["Metti a bollire l'acqua per la pasta in una pentola capiente.", "Taglia il guanciale a striscioline e rosolalo in padella senza olio finché diventa croccante.", "Sbatti i tuorli in una ciotola insieme al formaggio grattugiato e a un pizzico di pepe.", "Scola la pasta al dente, uniscila al guanciale fuori dal fuoco e versa il composto di uova mescolando rapidamente."],
    tip: "Se la crema risulta troppo densa, aggiungi un cucchiaio di acqua di cottura della pasta fuori dal fuoco per non far coagulare l'uovo.",
    art: "/graphics/onion.jpg",
    baseServings: 2,
  },
  {
    id: "gnocchi-sorrentina",
    title: "Gnocchi alla sorrentina express",
    description:
      "Gnocchi filanti affogati nel pomodoro e mozzarella, passati velocemente in forno.",
    minutes: 20,
    diet: "vegetarian",
    tags: ["gnocchi", "pomodori", "mozzarella", "parmigiano"],
    ingredients: ["400 g di gnocchi di patate", "250 g di passata di pomodoro", "125 g di mozzarella", "20 g di parmigiano", "olio extravergine e basilico q.b."],
    steps: ["Scalda la passata di pomodoro in una padella con un filo d'olio, sale e basilico per 10 minuti.", "Cuoci gli gnocchi in acqua bollente salata e scolali non appena salgono a galla.", "Condisci gli gnocchi con il sugo di pomodoro e cubetti di mozzarella.", "Trasferisci in una pirofila, spolvera di parmigiano e passa sotto il grill del forno per 5 minuti."],
    tip: "Fai sgocciolare bene la mozzarella prima di tagliarla a cubetti per evitare che rilasci troppa acqua nel sugo.",
    art: "/graphics/tomato.jpg",
    baseServings: 2,
  },
  {
    id: "pasta-alla-checca",
    title: "Pasta alla checca",
    description:
      "Un primo piatto freddo o tiepido tipico laziale, perfetto per l'estate con ingredienti crudi.",
    minutes: 12,
    diet: "vegetarian",
    tags: ["pasta", "pomodori", "mozzarella", "basilico"],
    ingredients: ["160 g di penne o fusilli", "150 g di pomodori ramati o ciliegini", "100 g di mozzarella o caciotta", "10 foglie di basilico fresco", "olio extravergine e sale q.b."],
    steps: ["Cuoci la pasta in abbondante acqua salata e scolala al dente.", "Taglia i pomodori e la mozzarella a piccoli cubetti dentro un'insalatiera capiente.", "Condisci il mix crudo con olio extravergine d'oliva, sale e abbondante basilico spezzettato a mano.", "Unisci la pasta calda o tiepida nella ciotola, mescola bene e servi immediatamente."],
    tip: "Puoi arricchire il piatto aggiungendo un cucchiaio di pinoli tostati o scaglie di parmigiano prima di servire.",
    art: "/graphics/tomato.jpg",
    baseServings: 2,
  },
  {
    id: "risotto-zucchine",
    title: "Risotto cremoso alle zucchine",
    description:
      "Un grande classico leggero e delicato, mantecato alla perfezione con il parmigiano.",
    minutes: 25,
    diet: "vegetarian",
    tags: ["riso", "zucchine", "parmigiano", "burro"],
    ingredients: ["160 g di riso Carnaroli o Arborio", "2 zucchine", "1/2 cipolla bionda", "30 g di parmigiano", "15 g di burro", "700 ml di brodo vegetale"],
    steps: ["Trita la cipolla e falla appassire in una casseruola con un filo d'olio e metà del burro.", "Grattugia le zucchine a fori larghi e aggiungile in casseruola lasciandole insaporire per 3 minuti.", "Tosta il riso per 2 minuti, poi porta a cottura aggiungendo il brodo caldo un mestolo alla volta.", "Spegni il fuoco, aggiungi il burro rimasto e il parmigiano, quindi manteca energicamente."],
    tip: "Manteca sempre a fuoco spento lasciando riposare il risotto coperto per 1 minuto prima di impiattare.",
    art: "/graphics/onion.jpg",
    baseServings: 2,
  },
  {
    id: "frittata-pasta-riciclata",
    title: "Frittata di pasta riciclata",
    description:
      "Il modo migliore e più gustoso per recuperare la pasta avanzata del giorno prima.",
    minutes: 15,
    diet: "vegetarian",
    tags: ["pasta", "uova", "parmigiano", "latte"],
    ingredients: ["200 g di pasta avanzata (condita o in bianco)", "3 uova", "20 g di parmigiano grattugiato", "2 cucchiai di latte", "olio extravergine, sale e pepe q.b."],
    steps: ["Sbatti le uova in una ciotola capiente insieme al latte, parmigiano, sale e pepe.", "Aggiungi la pasta avanzata nella ciotola e mescola bene per distribuire l'uovo uniformemente.", "Scalda un filo d'olio in una padella antiaderente e versa tutto il composto livellandolo con una forchetta.", "Cuoci a fuoco medio con coperchio per 5 minuti per lato, girandola aiutandoti con il coperchio stesso."],
    tip: "Se la pasta avanzata è in bianco, aggiungi dei cubetti di prosciutto cotto o mozzarella all'impasto.",
    art: "/graphics/onion.jpg",
    baseServings: 2,
  },
  {
    id: "spaghetti-aglio-olio-peperoncino-classico",
    title: "Spaghetti aglio, olio e peperoncino",
    description:
      "Il salva-cena di mezzanotte per antonomasia, piccante e profumato, con pochissimi ingredienti.",
    minutes: 10,
    diet: "vegan",
    tags: ["pasta", "aglio", "peperoncino", "olio"],
    ingredients: ["180 g di spaghetti", "2 spicchi d'aglio", "1 peperoncino fresco o secco", "4 cucchiai di olio extravergine", "prezzemolo fresco q.b."],
    steps: ["Cuoci gli spaghetti in acqua bollente leggermente meno salata del solito.", "Schiaccia gli spicchi d'aglio e falli dorare a fuoco bassissimo in padella con l'olio e il peperoncino tritato.", "Scola la pasta due minuti prima del tempo e saltala nella padella con il condimento.", "Aggiungi un mestolo di acqua di cottura e mescola energicamente per creare un'emulsione cremosa."],
    tip: "Non far bruciare l'aglio, altrimenti il condimento prenderà un sapore amaro sgradevole.",
    art: "/graphics/pepper.jpg",
    baseServings: 2,
  },
  {
    id: "pasta-ricotta-pepe",
    title: "Pasta alla ricotta e pepe",
    description:
      "Una crema vellutata e avvolgente senza cottura, ideale quando si ha pochissimo tempo.",
    minutes: 12,
    diet: "vegetarian",
    tags: ["pasta", "ricotta", "parmigiano", "pepe"],
    ingredients: ["160 g di pasta (corta o lunga)", "150 g di ricotta vaccina o di pecora", "20 g di parmigiano", "pepe nero macinato fresco q.b.", "sale q.b."],
    steps: ["Cuoci la pasta nella forma preferita in abbondante acqua salata.", "Lavora la ricotta in una ciotola con una forchetta fino a renderla una crema liscia.", "Aggiungi alla ricotta il parmigiano, abbondante pepe nero e due cucchiai di acqua di cottura della pasta.", "Scola la pasta, versala direttamente nella ciotola con la ricotta e mescola fino a renderla omogenea."],
    tip: "Scegli una ricotta freschissima e lasciala fuori dal frigo 10 minuti prima di utilizzarla.",
    art: "/graphics/lettuce.jpg",
    baseServings: 2,
  },
  {
    id: "vellutata-svuotafrigo",
    title: "Vellutata confortevole svuotafrigo",
    description:
      "Un caldo comfort food per riciclare tutte le verdure rimaste nel cassetto del frigorifero.",
    minutes: 30,
    diet: "vegetarian",
    tags: ["verdure", "zucchine", "carote", "patate"],
    ingredients: ["400 g di verdure miste (zucchine, carote, patate, pomodori)", "1/2 cipolla", "2 cucchiai di olio extravergine", "crostini di pane q.b.", "10 g di parmigiano"],
    steps: ["Pela, lava e taglia a cubetti regolari tutte le verdure a disposizione.", "In una pentola fai appassire la cipolla con l'olio, poi unisci le verdure e copri d'acqua.", "Porta a bollore e cuoci a fuoco medio per circa 20-25 minuti fino a quando le patate sono tenere.", "Frulla il tutto con un mixer a immersione fino a ottenere una crema liscia, servendo con crostini e parmigiano."],
    tip: "Una patata inserita nel mix è il segreto per dare la consistenza vellutata e densa al piatto.",
    art: "/graphics/onion.jpg",
    baseServings: 2,
  },
  {
    id: "pennette-campagnola",
    title: "Pennette alla campagnola",
    description:
      "Un primo piatto rustico arricchito dal sapore deciso della salsiccia sbriciolata.",
    minutes: 20,
    diet: "omnivore",
    tags: ["pasta", "salsiccia", "pomodori", "cipolla"],
    ingredients: ["160 g di pennette rigate", "1 salsiccia fresca", "150 g di passata di pomodoro", "1/4 di cipolla bionda", "olio extravergine e sale q.b."],
    steps: ["Sgrana la salsiccia eliminando il budello e spezzettandola finemente con le mani.", "Rosola la cipolla tritata in padella con un filo d'olio, poi unisci la salsiccia e lasciala dorare.", "Versa la passata di pomodoro, regola di sale e lascia cuocere a fuoco lento per 15 minuti.", "Cuoci la pasta, scolala al dente e saltala direttamente nel sugo rustico prima di servire."],
    tip: "Sfumare la salsiccia con un goccio di vino bianco prima di mettere il pomodoro eleva il sapore del piatto.",
    art: "/graphics/tomato.jpg",
    baseServings: 2,
  },
  {
    id: "risotto-pomodoro-mozzarella",
    title: "Risotto al pomodoro e mozzarella filante",
    description:
      "Un risotto semplice amato da grandi e bambini, dal cuore incredibilmente filante.",
    minutes: 25,
    diet: "vegetarian",
    tags: ["riso", "pomodori", "mozzarella", "burro"],
    ingredients: ["160 g di riso per risotti", "200 g di passata di pomodoro", "100 g di mozzarella", "600 ml di brodo vegetale", "cipolla e burro q.b."],
    steps: ["Tosta il riso nella casseruola dopo aver fatto appassire un po' di cipolla tritata nel burro.", "Unisci la passata di pomodoro e prosegui la cottura aggiungendo il brodo bollente poco alla volta.", "Taglia la mozzarella a cubetti molto piccoli e tienila da parte.", "A fuoco spento manteca con una noce di burro e unisci la mozzarella, mescolando finché non fila."],
    tip: "Servi immediatamente nei piatti per godere al massimo dell'effetto filante caldo della mozzarella.",
    art: "/graphics/tomato.jpg",
    baseServings: 2,
  },
  {
    id: "orecchiette-salsiccia-zucchine",
    title: "Orecchiette salsiccia e zucchine",
    description:
      "Un abbinamento azzeccato tra la dolcezza delle zucchine e la sapidità della salsiccia.",
    minutes: 20,
    diet: "omnivore",
    tags: ["pasta", "salsiccia", "zucchine", "aglio"],
    ingredients: ["160 g di orecchiette fresche o secche", "1 salsiccia", "1 zucchina grande", "1 spicchio d'aglio", "olio extravergine e sale q.b."],
    steps: ["Taglia la zucchina a rondelle sottili o a piccoli cubetti.", "In una padella fai dorare l'aglio con l'olio, unisci la salsiccia sgranata e cuoci per 5 minuti.", "Aggiungi le zucchine nella stessa padella e salta a fuoco vivo per altri 7-8 minuti.", "Cuoci le orecchiette, scolale e saltale nel condimento unendo un filo d'olio a crudo."],
    tip: "Mantieni le zucchine leggermente croccanti per dare una consistenza piacevole al piatto.",
    art: "/graphics/onion.jpg",
    baseServings: 2,
  },
  {
    id: "pasta-boscaiola-veloce",
    title: "Pasta alla boscaiola veloce",
    description:
      "Saporita e avvolgente, una finta boscaiola con ingredienti facili da dispensa.",
    minutes: 20,
    diet: "omnivore",
    tags: ["pasta", "prosciutto cotto", "funghi", "panna"],
    ingredients: ["160 g di penne rigate", "80 g di prosciutto cotto a dadini", "100 g di funghi champignon (freschi o surgelati)", "3 cucchiai di passata di pomodoro", "50 g di panna da cucina o ricotta"],
    steps: ["In una padella scalda un filo d'olio e rosola i cubetti di prosciutto cotto insieme ai funghi.", "Aggiungi la passata di pomodoro e cuoci a fuoco medio per circa 10 minuti.", "Unisci la panna (o la ricotta stemperata con acqua) per creare una salsa rosa e densa.", "Tuffa la pasta scolata al dente nella padella e amalgama il tutto prima di impiattare."],
    tip: "Se usi la ricotta al posto della panna otterrai una versione più leggera ma altrettanto cremosa.",
    art: "/graphics/mushrooms.jpg",
    baseServings: 2,
  },
  {
    id: "risotto-parmigiano-pepe",
    title: "Risotto al parmigiano e pepe",
    description:
      "La versione risotto della celebre pasta cacio e pepe, chic e facilissima.",
    minutes: 22,
    diet: "vegetarian",
    tags: ["riso", "parmigiano", "burro", "pepe"],
    ingredients: ["160 g di riso Arborio o Carnaroli", "50 g di parmigiano reggiano grattugiato", "20 g di burro", "pepe nero in grani q.b.", "600 ml di brodo vegetale leggero"],
    steps: ["Tosta il riso a secco in una casseruola per un paio di minuti finché i chicchi sono caldi.", "Bagna con il brodo bollente e porta a cottura mescolando di tanto in tanto.", "Nel frattempo, pesta il pepe nero in un mortaio o macinalo grossolanamente al momento.", "Spegni il fuoco, aggiungi il burro, il parmigiano e il pepe pestato, mescolando vigorosamente all'onda."],
    tip: "Tostare il pepe nero da solo in un padellino per 30 secondi sprigiona gli oli essenziali e raddoppia il profumo.",
    art: "/graphics/pepper.jpg",
    baseServings: 2,
  },
  {
    id: "pasta-del-maresciallo",
    title: "Pasta del maresciallo",
    description:
      "Un primo super cremoso con una salsa densa a base di pomodoro, panna e pancetta.",
    minutes: 15,
    diet: "omnivore",
    tags: ["pasta", "pancetta", "pomodori", "panna"],
    ingredients: ["160 g di rigatoni o penne", "80 g di pancetta affumicata o dolce", "150 g di passata di pomodoro", "60 g di panna da cucina", "cipolla e olio q.b."],
    steps: ["Fai appassire pochissima cipolla tritata in padella con l'olio e aggiungi la pancetta a dadini.", "Quando la pancetta è dorata, versa la passata di pomodoro e fai restringere per 8 minuti.", "Versa la panna da cucina nel sugo di pomodoro mescolando fino a ottenere un colore omogeneo.", "Scola i rigatoni ben al dente e finisci la cottura saltandoli nella salsa cremosa."],
    tip: "Puoi sostituire la pancetta con il prosciutto cotto se preferisci un gusto più delicato.",
    art: "/graphics/tomato.jpg",
    baseServings: 2,
  },
  {
    id: "gnocchi-zucchine-speck",
    title: "Gnocchi zucchine e speck",
    description:
      "Un abbinamento intramontabile e rapidissimo, ideale per un pranzo dell'ultimo minuto.",
    minutes: 15,
    diet: "omnivore",
    tags: ["gnocchi", "zucchine", "speck", "ricotta"],
    ingredients: ["400 g di gnocchi di patate", "70 g di speck o prosciutto crudo a listarelle", "1 zucchina", "50 g di formaggio spalmabile o ricotta", "olio extravergine q.b."],
    steps: ["Metti a scaldare l'acqua per gli gnocchi. Nel frattempo taglia la zucchina a julienne sottile.", "In una padella ampia rosola lo speck senza grassi finché diventa croccante, poi toglilo e tienilo da parte.", "Nella stessa padella metti un filo d'olio, salta le zucchine per 5 minuti e unisci il formaggio spalmabile.", "Cuoci gli gnocchi, scolali e saltali nella crema di zucchine, guarnendo alla fine con lo speck croccante."],
    tip: "Non salare il condimento prima di aver assaggiato: lo speck rilascia già molta sapidità.",
    art: "/graphics/onion.jpg",
    baseServings: 2,
  },
  {
    id: "puttanesca-veloce",
    title: "Spaghettata alla puttanesca veloce",
    description:
      "Un piatto della tradizione campana, ricco di aromi mediterranei e facilissimo da improvvisare.",
    minutes: 15,
    diet: "omnivore",
    tags: ["pasta", "pomodori", "olive", "capperi", "alici"],
    ingredients: ["160 g di spaghetti", "200 g di passata di pomodoro o polpa", "40 g di olive nere snocciolate", "1 cucchiaio di capperi sotto sale", "2 filetti di alici sott'olio", "aglio e peperoncino q.b."],
    steps: ["Sciogli i filetti di alici in padella con olio caldo, lo spicchio d'aglio e il peperoncino.", "Aggiungi le olive tagliate a rondelle, i capperi dissalati e infine la passata di pomodoro.", "Fai cuocere il sugo per circa 10 minuti a fuoco dolce finché non si addensa bene.", "Cuoci gli spaghetti, scolali al dente e tuffali nella padella girando velocemente."],
    tip: "Sciacqua i capperi sotto l'acqua corrente con cura per eliminare tutto il sale in eccesso.",
    art: "/graphics/tomato.jpg",
    baseServings: 2,
  },
  {
    id: "risotto-milanese-semplificato",
    title: "Risotto alla milanese semplificato",
    description:
      "Il risotto allo zafferano dorato e profumato, ridotto ai passaggi essenziali casalinghi.",
    minutes: 25,
    diet: "vegetarian",
    tags: ["riso", "zafferano", "burro", "parmigiano"],
    ingredients: ["160 g di riso Carnaroli o Arborio", "1 bustina di zafferano", "1/4 di cipolla bionda", "25 g di burro", "30 g di parmigiano grattugiato", "600 ml di brodo vegetale o di carne"],
    steps: ["Sciogli lo zafferano in mezza tazzina di brodo caldo preso dal totale.", "Soffriggi la cipolla tritata finemente in metà del burro fino a farla diventare trasparente.", "Tosta il riso per un minuto, poi bagna costantemente con il brodo portandolo a cottura.", "Negli ultimi due minuti versa lo zafferano sciolto e infine manteca fuori dal fuoco con il burro rimasto e il parmigiano."],
    tip: "Per un perfetto riso all'onda non farlo asciugare troppo prima della mantecatura finale.",
    art: "/graphics/onion.jpg",
    baseServings: 2,
  },
  {
    id: "pasta-del-campione",
    title: "Pasta del campione (uovo e parmigiano)",
    description:
      "La ricetta del comfort alimentare quando il frigo piange ma si vuole qualcosa di squisito.",
    minutes: 10,
    diet: "vegetarian",
    tags: ["pasta", "uova", "parmigiano", "burro"],
    ingredients: ["160 g di pasta corta (es. mezze maniche)", "1 uovo intero", "40 g di parmigiano reggiano", "20 g di burro di ottima qualità", "pepe nero q.b."],
    steps: ["Cuoci la pasta in acqua bollente salata secondo i tempi indicati sulla confezione.", "In una ciotola capiente sbatti energicamente l'uovo con il parmigiano e un pizzico di pepe.", "Scola la pasta lasciandola umida e versala bollente nella ciotola insieme al burro a pezzetti.", "Mescola velocemente in modo che il calore della pasta sciolga il burro e crei una cremina con l'uovo."],
    tip: "La ciotola deve essere preferibilmente calda per aiutare la fusione senza stracuocere l'uovo.",
    art: "/graphics/lemon.jpg",
    baseServings: 2,
  },
  {
    id: "fusilli-pomodori-secchi",
    title: "Fusilli alla crema di pomodori secchi",
    description:
      "Un primo piatto dal sapore concentrato e mediterraneo che si prepara nel tempo di cottura della pasta.",
    minutes: 15,
    diet: "vegetarian",
    tags: ["pasta", "pomodori secchi", "ricotta"],
    ingredients: ["160 g di fusilli", "6-7 pomodori secchi sott'olio", "60 g di ricotta o formaggio fresco", "10 g di mandorle o pinoli", "olio extravergine q.b."],
    steps: ["Metti a cuocere i fusilli in abbondante acqua bollente salata.", "Nel boccale del mixer inserisci i pomodori secchi ben sgocciolati, la ricotta, le mandorle e un filo d'olio.", "Frulla aggiungendo un mestolo di acqua di cottura della pasta fino a ottenere un pesto liscio.", "Versa la crema ottenuta in una terrina, unisci la pasta scolata al dente e amalgama con cura."],
    tip: "Fai attenzione al sale nell'acqua della pasta, poiché i pomodori secchi sono già molto sapidi.",
    art: "/graphics/tomato.jpg",
    baseServings: 2,
  },
  {
    id: "zuppa-lettere-formaggino",
    title: "Zuppa di lettere e formaggino",
    description:
      "Il piatto nostalgico e cremoso perfetto per le sere fredde o quando si vuole qualcosa di super leggero.",
    minutes: 12,
    diet: "vegetarian",
    tags: ["pastina", "formaggino", "brodo"],
    ingredients: ["100 g di pastina (letterine, stelline o risoni)", "500 ml di brodo vegetale", "2 formaggini o 80 g di ricotta", "10 g di parmigiano grattugiato"],
    steps: ["Porta a bollore il brodo vegetale in un pentolino.", "Versa la pastina e cuocila per il tempo indicato (solitamente dai 5 ai 7 minuti).", "Spegni il fuoco, aggiungi i formaggini e schiacciali con la forchetta per farli sciogliere completamente.", "Dai una generosa spolverata di parmigiano grattugiato e mescola prima di servire calda."],
    tip: "Regola la quantità di brodo alla fine se preferisci una consistenza più densa o più liquida.",
    art: "/graphics/lettuce.jpg",
    baseServings: 2,
  },
  {
    id: "tiramisu-bicchiere",
    title: "Tiramisù in bicchiere express",
    description:
      "La versione monodose e rapida del dolce italiano più famoso, senza albumi montati.",
    minutes: 15,
    diet: "vegetarian",
    tags: ["mascarpone", "caffè", "savoiardi", "dessert"],
    ingredients: ["150 g di mascarpone o ricotta", "1 tazza di caffè espresso zuccherato", "6 biscotti savoiardi o frollini", "30 g di zucchero a velo", "cacao amaro in polvere q.b."],
    steps: ["Lavora il mascarpone (o la ricotta) in una ciotola con lo zucchero a velo fino a creare una crema.", "Prepara il caffè e lascialo intiepidire in un piatto fondo.", "Spezza i biscotti a metà, inzuppali velocemente nel caffè e disponili sul fondo di due bicchieri.", "Copri con uno strato di crema, ripeti l'operazione e completa spolverando abbondante cacao amaro."],
    tip: "Non inzuppare troppo i biscotti nel caffè per evitare liquido sul fondo del bicchiere.",
    art: "/graphics/lettuce.jpg",
    baseServings: 2,
  },
  {
    id: "panna-cotta-marmellata",
    title: "Panna cotta espressa alla marmellata",
    description:
      "Un dolce al cucchiaio della pasticceria, velocizzato in bicchieri monoporzione.",
    minutes: 15,
    diet: "vegetarian",
    tags: ["panna", "marmellata", "dessert"],
    ingredients: ["200 ml di panna fresca liquida", "40 g di zucchero semolato", "2 g di gelatina in fogli (1 foglio)", "3 cucchiai di confettura di frutta", "1 cucchiaino di estratto di vaniglia"],
    steps: ["Ammolla il foglio di gelatina in acqua fredda per 10 minuti.", "In un pentolino scalda la panna con lo zucchero e la vaniglia senza farle bollire.", "Spegni il fuoco, strizza la gelatina e scioglila nella panna calda mescolando bene.", "Versa nei bicchieri e lascia rassodare in frigorifero per almeno 3 ore prima di guarnire con la marmellata."],
    tip: "Se hai fretta, metti i bicchieri in freezer per 30-45 minuti per accelerare la gelificazione.",
    art: "/graphics/lettuce.jpg",
    baseServings: 2,
  },
  {
    id: "mattonella-caffe-biscotti",
    title: "Mattonella al caffè e biscotti",
    description:
      "Un dolce freddo velocissimo che ricorda i sapori dell'infanzia e della colazione.",
    minutes: 15,
    diet: "vegetarian",
    tags: ["biscotti", "burro", "caffè", "dessert"],
    ingredients: ["12 biscotti secchi", "50 g di burro morbido a pomata", "40 g di zucchero", "2 tazzine di caffè ristretto freddo", "gocce di cioccolato q.b."],
    steps: ["Lavora il burro morbido con lo zucchero fino a ottenere una crema bianca e spumosa.", "Aggiungi un cucchiaino di caffè alla crema di burro continuando a mescolare.", "Inzuppa i biscotti secchi nel restante caffè e crea una torretta alternando biscotto e crema di burro.", "Ricopri l'ultimo strato con la crema rimasta e decora con le gocce di cioccolato prima di mettere in frigo."],
    tip: "Il burro deve essere a temperatura ambiente per almeno un'ora prima di essere lavorato.",
    art: "/graphics/lettuce.jpg",
    baseServings: 2,
  },
  {
    id: "crumble-frutta-padella",
    title: "Crumble di frutta in padella",
    description:
      "Una versione furbissima e croccante senza forno, ideale per consumare la frutta matura.",
    minutes: 15,
    diet: "vegetarian",
    tags: ["frutta", "biscotti", "burro", "dessert"],
    ingredients: ["2 pezzi di frutta di stagione (mele, pesche o fragole)", "40 g di biscotti secchi sbriciolati", "15 g di burro", "1 cucchiaio di zucchero di canna", "1 pizzico di cannella"],
    steps: ["Taglia la frutta a piccoli cubetti eliminando la buccia se necessario.", "In un pentolino salta la frutta con metà del burro, lo zucchero di canna e la cannella per 5 minuti.", "In un padellino a parte fai sciogliere il burro rimasto e tosta i biscotti sbriciolati per 2 minuti.", "Componi il dolce nei bicchieri mettendo la frutta calda sul fondo e il crumble di biscotti sopra."],
    tip: "Accompagna questo dolce tiepido con una pallina di gelato alla vaniglia o yogurt greco.",
    art: "/graphics/lettuce.jpg",
    baseServings: 2,
  },
  {
    id: "crema-pasticcera-microonde",
    title: "Crema pasticcera rapida al microonde",
    description:
      "Il segreto per una crema pasticcera setosa e densa in pochissimi minuti.",
    minutes: 8,
    diet: "vegetarian",
    tags: ["latte", "uova", "dessert"],
    ingredients: ["250 ml di latte", "2 tuorli d'uovo", "50 g di zucchero", "20 g di amido di mais (Maizena) o farina", "1 pezzetto di scorza di limone"],
    steps: ["In una ciotola adatta al microonde sbatti i tuorli con lo zucchero e l'amido fino a eliminare i grumi.", "Versa il latte a filo continuando a mescolare e inserisci la scorza di limone.", "Cuoci in microonde a 750W per 2 minuti, estrai, mescola bene e cuoci per un altro minuto.", "Ripeti se necessario finché la crema non si addensa, poi elimina la scorza di limone."],
    tip: "Copri subito la crema con pellicola a contatto per evitare la pellicina in superficie.",
    art: "/graphics/lemon.jpg",
    baseServings: 2,
  },
  {
    id: "banane-caramellate",
    title: "Banane caramellate al burro",
    description:
      "Un dessert caldo e avvolgente che trasforma un frutto comune in una golosità da fine pasto.",
    minutes: 10,
    diet: "vegetarian",
    tags: ["banane", "burro", "dessert"],
    ingredients: ["2 banane mature ma salde", "20 g di burro", "2 cucchiai di zucchero di canna", "1 cucchiaio di succo di limone"],
    steps: ["Sbuccia le banane e tagliale in due parti per il lungo o a rondelle spesse.", "In una padella antiaderente fai sciogliere il burro insieme allo zucchero di canna e al succo di limone.", "Adagia le banane e cuocile a fuoco medio per 3 minuti per lato finché non saranno dorate.", "Versa la salsina al caramello rimasta in padella sopra le banane calde prima di servire."],
    tip: "Gira le banane con delicatezza per evitare che si sfaldino durante la cottura.",
    art: "/graphics/lemon.jpg",
    baseServings: 2,
  },
  {
    id: "mousse-yogurt-marmellata",
    title: "Mousse rapida allo yogurt e marmellata",
    description:
      "Un dessert freschissimo, leggero e spumoso con ingredienti da frigo.",
    minutes: 10,
    diet: "vegetarian",
    tags: ["yogurt", "panna", "marmellata", "dessert"],
    ingredients: ["200 g di yogurt greco bianco o alla vaniglia", "100 ml di panna da montare", "3 cucchiai di confettura di frutta o miele", "1 cucchiaio di zucchero a velo"],
    steps: ["Monta la panna ben fredda a neve ferma insieme allo zucchero a velo.", "In una ciotola ammorbidisci lo yogurt greco mescolandolo velocemente.", "Incorpora la panna montata allo yogurt con movimenti delicati dal basso verso l'alto.", "Distribuisci la mousse nei bicchieri e guarnisci con un generoso strato di marmellata."],
    tip: "Usa lo yogurt greco: la consistenza compatta evita che la mousse diventi troppo liquida.",
    art: "/graphics/lettuce.jpg",
    baseServings: 2,
  },
  {
    id: "mug-cake-cioccolato",
    title: "Tortino al cioccolato in tazza (mug cake)",
    description:
      "La torta in tazza al microonde, soluzione d'emergenza per le voglie notturne.",
    minutes: 5,
    diet: "vegetarian",
    tags: ["cacao", "latte", "farina", "dessert"],
    ingredients: ["3 cucchiai di farina 00", "2 cucchiai di zucchero", "1 cucchiaio di cacao amaro", "3 cucchiai di latte", "1 cucchiaio di burro fuso o olio", "1 punta di cucchiaino di lievito per dolci"],
    steps: ["Inserisci gli ingredienti secchi direttamente in una tazza da colazione e mescola.", "Aggiungi latte e burro fuso amalgamando bene.", "Pulisci i bordi e cuoci nel microonde a 800W per circa 90 secondi.", "Lascia intiepidire un minuto prima di gustare con il cucchiaino."],
    tip: "Non cuocere oltre il tempo indicato altrimenti il tortino diventa gommoso.",
    art: "/graphics/lettuce.jpg",
    baseServings: 1,
  },
  {
    id: "crepes-marmellata",
    title: "Crepes dolci alla marmellata",
    description:
      "Le crespelle intramontabili, sottili e profumate, ripiene della confettura preferita.",
    minutes: 20,
    diet: "vegetarian",
    tags: ["farina", "latte", "uova", "marmellata", "dessert"],
    ingredients: ["60 g di farina 00", "120 ml di latte", "1 uovo", "burro per la padella q.b.", "4 cucchiai di confettura o marmellata"],
    steps: ["In una ciotola sbatti l'uovo con la farina e versa il latte a filo per evitare grumi.", "Lascia riposare la pastella per 10 minuti a temperatura ambiente.", "Scalda un velo di burro in padella antiaderente e versa un mestolino di pastella.", "Cuoci 1 minuto per lato, farcisci con la marmellata e piega la crepe in quattro."],
    tip: "La padella deve essere caldissima prima di versare il primo mestolo di pastella.",
    art: "/graphics/lemon.jpg",
    baseServings: 2,
  },
  {
    id: "budino-cioccolato",
    title: "Budino al cioccolato senza bustina",
    description:
      "Fare il budino al cioccolato in casa è un gioco da ragazzi, senza preparati industriali.",
    minutes: 20,
    diet: "vegetarian",
    tags: ["latte", "cacao", "dessert"],
    ingredients: ["250 ml di latte intero", "25 g di cacao amaro", "50 g di zucchero semolato", "20 g di burro", "20 g di amido di mais (Maizena)"],
    steps: ["In un pentolino unisci zucchero, cacao e amido setacciato.", "Versa il latte a filo mescolando con una frusta per sciogliere i grumi.", "Metti sul fuoco medio-basso e continua a mescolare fino a quando il composto si addensa.", "Togli dal fuoco, aggiungi il burro a pezzetti e versa il budino nelle coppette."],
    tip: "Per evitare la crosticina in superficie, copri le coppette con pellicola a contatto.",
    art: "/graphics/lettuce.jpg",
    baseServings: 2,
  },
  {
    id: "mele-forno-golose",
    title: "Mele al forno con cuore goloso",
    description:
      "Un dessert della nonna caldo e salutare, arricchito da una farcitura croccante.",
    minutes: 25,
    diet: "vegetarian",
    tags: ["mele", "marmellata", "biscotti", "dessert"],
    ingredients: ["2 mele (Renette o Golden)", "2 cucchiai di marmellata di albicocche o pesche", "2 biscotti secchi sbriciolati", "2 tocchetti di burro", "cannella q.b."],
    steps: ["Lava le mele e rimuovi il torsolo centrale lasciando la base intatta.", "Mescola la marmellata con i biscotti sbriciolati e un pizzico di cannella.", "Riempi la cavità delle mele e adagia sopra ciascuna un tocchetto di burro.", "Metti in teglia con due cucchiai d'acqua e inforna a 190°C per 20-25 minuti."],
    tip: "Le mele sono cotte quando la buccia inizia a raggrinzirsi e risultano morbide alla forchetta.",
    art: "/graphics/lettuce.jpg",
    baseServings: 2,
  },
  {
    id: "tartufini-ricotta-cacao",
    title: "Tartufini express ricotta e cacao",
    description:
      "Piccole sfere cioccolatose senza cottura, pronte in pochi passaggi.",
    minutes: 10,
    diet: "vegetarian",
    tags: ["ricotta", "biscotti", "cacao", "dessert"],
    ingredients: ["120 g di ricotta vaccina ben sgocciolata", "60 g di biscotti secchi polverizzati", "40 g di zucchero a velo", "2 cucchiai di cacao amaro + q.b. per la copertura"],
    steps: ["Unisci la ricotta con lo zucchero a velo lavorandola a crema.", "Aggiungi i biscotti tritati e i due cucchiai di cacao amaro.", "Mescola fino a ottenere un impasto sodo e modellabile.", "Forma delle palline e rotolale nel cacao amaro rimasto."],
    tip: "Lascia riposare i tartufini in frigorifero per 20 minuti prima di servirli.",
    art: "/graphics/lettuce.jpg",
    baseServings: 2,
  },
  {
    id: "rotolo-pane-tramezzini-dolce",
    title: "Rotolo di pane per tramezzini dolce",
    description:
      "Un'idea furbissima che trasforma il pane bianco in un dolcetto da tagliare a fette.",
    minutes: 15,
    diet: "vegetarian",
    tags: ["pane", "marmellata", "burro", "dessert"],
    ingredients: ["2 fette lunghe di pane per tramezzini (senza crosta)", "3 cucchiai di confettura o marmellata", "10 g di burro fuso", "1 cucchiaio di zucchero di canna"],
    steps: ["Appiattisci le fette di pane con un mattarello.", "Spalma un velo generoso di marmellata su tutta la superficie.", "Arrotola dal lato corto stringendo bene per formare cilindri compatti.", "Spennella con burro fuso, passa nello zucchero di canna e dora in padella per 3 minuti."],
    tip: "Taglia i rotoli a fette solo dopo che si sono leggermente raffreddati.",
    art: "/graphics/lettuce.jpg",
    baseServings: 2,
  },
  {
    id: "crema-limone-acqua",
    title: "Crema al limone all'acqua (senza latte)",
    description:
      "Una crema vellutata e profumata, senza lattosio e uova, rinfrescante.",
    minutes: 15,
    diet: "vegan",
    tags: ["limone", "dessert"],
    ingredients: ["250 ml di acqua", "40 ml di succo di limone filtrato", "60 g di zucchero", "25 g di amido di mais (Maizena)", "scorza di 1 limone grattugiata"],
    steps: ["Unisci zucchero e amido di mais in un pentolino.", "Versa l'acqua a filo mescolando con una frusta per non formare grumi.", "Aggiungi scorza e succo di limone, poi metti sul fuoco medio.", "Porta a bollore girando finché la crema non diventa densa e lucida, poi lascia raffreddare."],
    tip: "Grattugia solo la parte gialla della buccia: il bianco lascia retrogusto amaro.",
    art: "/graphics/lemon.jpg",
    baseServings: 2,
  },
  {
    id: "bicchiere-yogurt-biscotti",
    title: "Bicchiere sfizioso yogurt e biscotti",
    description:
      "Il dessert dell'ultimo secondo a strati, bello da vedere e leggero.",
    minutes: 5,
    diet: "vegetarian",
    tags: ["yogurt", "biscotti", "marmellata", "dessert"],
    ingredients: ["250 g di yogurt bianco cremoso", "6 biscotti secchi o frollini", "2 cucchiai di marmellata o miele", "gocce di cioccolato q.b."],
    steps: ["Sbriciola i biscotti sul fondo di due bicchieri di vetro.", "Copri con un generoso strato di yogurt.", "Aggiungi un cucchiaio di marmellata o miele in modo uniforme.", "Decora con gocce di cioccolato o biscotti sbriciolati."],
    tip: "Prepara poco prima di servire se ami il biscotto ancora croccante.",
    art: "/graphics/lettuce.jpg",
    baseServings: 2,
  },
  {
    id: "omelette-dolce-marmellata",
    title: "Omelette dolce soufflé alla marmellata",
    description:
      "Una frittatina dolce gonfia e soffice, ripiegata su un cuore fruttato.",
    minutes: 15,
    diet: "vegetarian",
    tags: ["uova", "marmellata", "dessert"],
    ingredients: ["2 uova", "1 cucchiaio di zucchero semolato", "10 g di burro", "2 cucchiai di confettura o marmellata", "zucchero a velo q.b."],
    steps: ["Separa i tuorli dagli albumi. Monta gli albumi a neve con lo zucchero.", "Sbatti leggermente i tuorli e incorporali delicatamente agli albumi.", "Sciogli il burro in padella antiaderente, versa il composto e copri per 4 minuti.", "Spalma la marmellata su metà omelette, piegala a libro e spolvera di zucchero a velo."],
    tip: "Cottura a fuoco molto basso per gonfiare senza bruciare.",
    art: "/graphics/lemon.jpg",
    baseServings: 1,
  },
  {
    id: "french-toast-dolce",
    title: "French toast dolce della dispensa",
    description:
      "La colazione-dessert internazionale con ingredienti sempre presenti in cucina.",
    minutes: 10,
    diet: "vegetarian",
    tags: ["pane", "uova", "latte", "dessert"],
    ingredients: ["4 fette di pane (anche raffermo)", "1 uovo", "50 ml di latte", "15 g di burro", "zucchero e cannella q.b."],
    steps: ["In un piatto fondo sbatti l'uovo con il latte e un pizzico di cannella.", "Passa le fette di pane nel composto su entrambi i lati.", "In padella sciogli il burro e scotta le fette finché non si forma una crosticina dorata.", "Passa le fette calde in un piatto con zucchero e cannella miscelati."],
    tip: "Il pane leggermente raffermo assorbe meglio l'uovo senza sfaldarsi.",
    art: "/graphics/lemon.jpg",
    baseServings: 2,
  },
  {
    id: "finti-cioccolatini",
    title: "Finti cioccolatini svuota-dispensa",
    description:
      "Piccoli bocconcini croccanti per riciclare rimasugli di biscotti o cereali.",
    minutes: 15,
    diet: "vegetarian",
    tags: ["cioccolato", "biscotti", "dessert"],
    ingredients: ["100 g di cioccolato fondente o al latte", "40 g di biscotti secchi o cornflakes tritati", "10 g di burro"],
    steps: ["Spezzetta il cioccolato e fallo sciogliere a bagnomaria o al microonde con il burro.", "Togli dal calore e unisci i biscotti sbriciolati.", "Mescola per rivestire tutti i pezzi di biscotto.", "Disponi a cucchiaiate su carta forno e lascia solidificare in frigo."],
    tip: "Puoi aggiungere uvetta o frutta secca se ti è rimasta in dispensa.",
    art: "/graphics/lettuce.jpg",
    baseServings: 2,
  },
  {
    id: "crema-cioccolato-acqua",
    title: "Crema pasticcera al cioccolato all'acqua",
    description:
      "Una variante vellutata senza latte né uova, ideale come fine pasto leggero.",
    minutes: 15,
    diet: "vegan",
    tags: ["cacao", "dessert"],
    ingredients: ["250 ml di acqua", "50 g di zucchero semolato", "20 g di cacao amaro", "20 g di amido di mais", "20 g di cioccolato fondente (opzionale)"],
    steps: ["Setaccia amido e cacao in un pentolino insieme allo zucchero.", "Aggiungi l'acqua a filo lentamente mescolando con la frusta.", "Metti sul fuoco medio e fai addensare mescolando continuamente.", "Spegni e, se vuoi, sciogli pezzetti di cioccolato fondente con il calore della crema."],
    tip: "Servi tiepida con qualche biscotto secco da intingere.",
    art: "/graphics/lettuce.jpg",
    baseServings: 2,
  },
  {
    id: "granita-limone",
    title: "Granita rapida al limone da freezer",
    description:
      "Il dessert ghiacciato dissetante tipico dell'estate, in versione semplificata.",
    minutes: 15,
    diet: "vegan",
    tags: ["limone", "dessert"],
    ingredients: ["250 ml di acqua", "80 ml di succo di limone filtrato", "60 g di zucchero"],
    steps: ["In un pentolino sciogli lo zucchero nell'acqua calda fino a uno sciroppo limpido, poi raffredda.", "Unisci il succo di limone allo sciroppo freddo e mescola.", "Versa in un contenitore basso e largo e metti in freezer.", "Ogni 30-40 minuti gratta con una forchetta per rompere i cristalli, ripetendo 3 volte."],
    tip: "Rompere i cristalli spesso è fondamentale per la consistenza granulosa.",
    art: "/graphics/lemon.jpg",
    baseServings: 2,
  },
];
