import type { Recipe } from "./types";

type BookRecipe = Omit<Recipe, "missing" | "servings"> & {
  tags: string[];
  baseServings: number;
};

/** Ricette svuotafrigo standardizzate (tradizione di casa). */
export const RECIPES_CLASSIC: BookRecipe[] = [
  {
    id: "frittata-zucchine-prosciutto",
    title: "Frittata ricca alle zucchine e prosciutto",
    description:
      "Spessa, soffice e dorata in superficie: una frittata casalinga arricchita con zucchine saltate e cubetti di prosciutto cotto. Perfetta per salvare una cena dell'ultimo minuto unendo proteine e verdure in un solo piatto.",
    minutes: 15,
    diet: "omnivore",
    tags: ["uova", "zucchine", "prosciutto cotto", "parmigiano"],
    ingredients: [
      "4 uova medie",
      "1 zucchina grande",
      "70 g di prosciutto cotto in una sola fetta",
      "2 cucchiai di parmigiano reggiano grattugiato",
      "2 cucchiai di olio extravergine",
      "sale e pepe",
    ],
    steps: [
      "Lava la zucchina e tagliala a rondelle sottili. Riduci il prosciutto cotto a cubetti.",
      "Scalda l'olio in una padella antiaderente, aggiungi le zucchine e cuoci per 5 minuti a fuoco vivo finché non sono tenere.",
      "In una ciotola sbatti le uova con il parmigiano reggiano, un pizzico di sale e una spolverata di pepe.",
      "Unisci i cubetti di prosciutto alle zucchine nella padella, quindi versa il composto di uova in modo uniforme.",
      "Cuoci a fuoco medio-basso per 4 minuti per lato, girando la frittata a metà cottura con l'aiuto di un piatto o di un coperchio.",
      "Servi subito ben calda o tiepida.",
    ],
    tip: "Non sbattere troppo a lungo le uova: è sufficiente amalgamare tuorli e albumi senza incorporare troppa aria, così la frittata rimarrà compatta e umida al centro.",
    art: "/graphics/onion.jpg",
    baseServings: 2,
  },
  {
    id: "caprese-calda-forno",
    title: "Caprese calda al forno",
    description:
      "Una rivisitazione invernale e filante del grande classico estivo: pomodori succosi e mozzarella fresca cotti al forno fino a creare una crosticina dorata e irresistibile.",
    minutes: 15,
    diet: "vegetarian",
    tags: ["pomodori", "mozzarella", "parmigiano", "origano"],
    ingredients: [
      "2 pomodori ramati grandi",
      "125 g di mozzarella fresca",
      "1 cucchiaio di parmigiano reggiano grattugiato",
      "1 cucchiaio di olio extravergine",
      "sale, pepe e origano",
    ],
    steps: [
      "Lava i pomodori e tagliali a fette spesse circa un centimetro. Taglia anche la mozzarella a fette simili.",
      "Disponi le fette di pomodoro e mozzarella alternate in una pirofila leggermente oliata.",
      "Condisci la superficie con un pizzico di sale, pepe nero e una generosa manciata di origano secco.",
      "Spolvera con il parmigiano reggiano grattugiato e rifinisci con un filo d'olio a crudo.",
      "Inforna sotto il grill preriscaldato a 200°C per circa 8-10 minuti, fino a quando la mozzarella non sarà completamente fusa e dorata.",
      "Estrai dal forno e lascia riposare due minuti prima di servire.",
    ],
    tip: "Fai scolare molto bene la mozzarella prima di tagliarla, premendola leggermente con carta assorbente: eviterai che rilasci troppa acqua sul fondo della pirofila durante la cottura.",
    art: "/graphics/tomato.jpg",
    baseServings: 2,
  },
  {
    id: "omelette-ricotta-prosciutto-crudo",
    title: "Omelette alla ricotta e prosciutto crudo",
    description:
      "Un guscio di uova morbido e ripiegato che racchiude un cuore cremoso di ricotta fresca e la sapidità del prosciutto crudo. Elegante nella sua estrema semplicità.",
    minutes: 12,
    diet: "omnivore",
    tags: ["uova", "ricotta", "prosciutto crudo", "burro"],
    ingredients: [
      "2 uova medie",
      "60 g di ricotta fresca",
      "2 fette di prosciutto crudo",
      "1 cucchiaino di burro",
      "sale e pepe",
    ],
    steps: [
      "In una ciotola lavora la ricotta con una forchetta insieme a un pizzico di sale e pepe fino a renderla una crema omogenea.",
      "Sbatti leggermente le uova in un'altra ciotola con un pizzico di sale.",
      "Sciogli il burro in una padella antiaderente a fuoco medio senza farlo scurire.",
      "Versa le uova e muovi la padella per distribuire il composto; solleva i bordi man mano che si rapprendono per far scivolare l'uovo liquido sotto.",
      "Quando la superficie è ancora leggermente umida, disponi il prosciutto crudo e la ricotta su una metà dell'omelette.",
      "Ripiega l'omelette a mezzaluna e cuoci ancora per 1 minuto prima di farla scivolare sul piatto da portata.",
    ],
    tip: "Mantieni il fuoco medio-basso durante tutta la cottura: l'omelette perfetta deve rimanere chiara all'esterno e baveuse (morbida e quasi cremosa) all'interno.",
    art: "/graphics/lemon.jpg",
    baseServings: 1,
  },
  {
    id: "risotto-parmigiano-salame",
    title: "Risotto saporito al parmigiano e salame",
    description:
      "Un risotto cremoso e dal carattere deciso, dove la dolcezza della mantecatura al parmigiano incontra la nota croccante e speziata del salame tostato in padella.",
    minutes: 25,
    diet: "omnivore",
    tags: ["riso", "salame", "parmigiano", "burro"],
    ingredients: [
      "160 g di riso Carnaroli o Arborio",
      "60 g di salame italiano",
      "40 g di parmigiano reggiano grattugiato",
      "20 g di burro",
      "1 litro di brodo vegetale leggero",
      "sale e pepe",
    ],
    steps: [
      "Taglia il salame a striscioline o dadini e tostalo in una casseruola senza grassi per 2 minuti finché non diventa croccante. Prelevalo e tienilo da parte.",
      "Nella stessa casseruola, sfrutta il grasso rilasciato dal salame per tostare il riso a secco per 2 minuti a fuoco vivo.",
      "Inizia ad aggiungere il brodo bollente un mestolo alla volta, mescolando spesso e aspettando che venga assorbito prima di aggiungerne altro.",
      "Porta il riso a cottura (circa 16-18 minuti) regolando di sale se necessario.",
      "Spegni il fuoco, aggiungi il salame croccante tenuto da parte, il burro freddo di frigo e il parmigiano reggiano.",
      "Mescola energicamente per mantecare il risotto, copri con un coperchio e lascia riposare per 2 minuti prima di servire con un pizzico di pepe.",
    ],
    tip: "Usa sempre burro freddissimo da frigorifero per la mantecatura: lo shock termico tra il riso bollente e il grasso freddo creerà un'emulsione perfetta ed eccezionalmente cremosa.",
    art: "/graphics/pepper.jpg",
    baseServings: 2,
  },
  {
    id: "zucchine-ripiene-ricotta-prosciutto",
    title: "Zucchine ripiene di ricotta e prosciutto cotto",
    description:
      "Barchette di zucchine scavate e farcite con una mousse leggera di ricotta, parmigiano e prosciutto cotto tritato, cotte in forno per una consistenza morbida ma compatta.",
    minutes: 35,
    diet: "omnivore",
    tags: ["zucchine", "ricotta", "prosciutto cotto", "parmigiano"],
    ingredients: [
      "2 zucchine lunghe medie",
      "150 g di ricotta fresca",
      "50 g di prosciutto cotto",
      "3 cucchiai di parmigiano reggiano grattugiato",
      "1 cucchiaio di olio extravergine",
      "sale, pepe e noce moscata",
    ],
    steps: [
      "Lava le zucchine, spuntale e tagliale a metà nel senso della lunghezza. Sbollentale in acqua salata per 5 minuti.",
      "Scola le zucchine, lasciale intiepidire e, usando un cucchiaino, scava delicatamente la polpa centrale lasciando un guscio solido.",
      "Trita finemente la polpa estratta e strizzala per eliminare l'acqua in eccesso; uniscila in una ciotola con ricotta, parmigiano e prosciutto cotto sminuzzato.",
      "Condisci il ripieno con un pizzico di sale, pepe e una grattugiata minima di noce moscata.",
      "Farcisci i gusci di zucchina con il composto ottenuto e disponili in una teglia unta con l'olio extravergine.",
      "Cuoci in forno preriscaldato a 190°C per circa 20 minuti, accendendo il grill negli ultimi 3 minuti per gratinare la superficie.",
    ],
    tip: "Se il ripieno dovesse risultare troppo umido a causa dell'acqua residua delle zucchine, aggiungi un cucchiaino di pangrattato al composto per renderlo più sodo.",
    art: "/graphics/onion.jpg",
    baseServings: 2,
  },
  {
    id: "bruschetta-pomodori-mozzarella",
    title: "Bruschetta golosa pomodori e mozzarella",
    description:
      "Fette di pane rustico tostate alla perfezione, strofinate con aglio e sormontate da un mix mediterraneo di pomodorini freschi e dadini di mozzarella filante.",
    minutes: 10,
    diet: "vegetarian",
    tags: ["pomodori", "mozzarella", "aglio", "pane"],
    ingredients: [
      "4 fette di pane casereccio",
      "2 pomodori maturi",
      "100 g di mozzarella",
      "1 spicchio d'aglio",
      "2 cucchiai di olio extravergine",
      "sale e origano",
    ],
    steps: [
      "Taglia i pomodori e la mozzarella a cubetti molto piccoli e raccoglili in una ciotola.",
      "Condisci il mix con l'olio extravergine, sale e una generosa spolverata di origano; lascia insaporire per 5 minuti.",
      "Tosta le fette di pane su una piastra ben calda o in forno per 2-3 minuti per lato, finché non risulteranno ben rigide e dorate.",
      "Strofina leggermente lo spicchio d'aglio pulito sulla superficie del pane caldo per rilasciare l'aroma.",
      "Distribuisci il condimento di pomodoro e mozzarella sopra le fette di pane ancora calde.",
      "Aggiungi un ultimo filo d'olio a crudo e servi immediatamente prima che il pane si inumidisca eccessivamente.",
    ],
    tip: "Taglia la mozzarella a cubetti e lasciala riposare in un colino prima di condire il pomodoro: in questo modo il pane rimarrà fragrante e super croccante senza inzupparsi.",
    art: "/graphics/tomato.jpg",
    baseServings: 2,
  },
  {
    id: "uova-in-purgatorio",
    title: "Uova in purgatorio al pomodoro e parmigiano",
    description:
      "Un piatto della tradizione povera campana: uova fresche cotte direttamente all'interno di un sugo denso di pomodoro, completate con abbondante parmigiano filante.",
    minutes: 15,
    diet: "vegetarian",
    tags: ["uova", "pomodori", "parmigiano", "aglio"],
    ingredients: [
      "4 uova medie",
      "300 g di passata di pomodoro",
      "1 spicchio d'aglio",
      "3 cucchiai di parmigiano reggiano grattugiato",
      "2 cucchiai di olio extravergine",
      "sale e pepe",
    ],
    steps: [
      "In una padella ampia scalda l'olio extravergine e fai dorare lo spicchio d'aglio intero schiacciato.",
      "Versa la passata di pomodoro, regola di sale e pepe e lascia cuocere a fuoco medio per 5-6 minuti fino a farla restringere leggermente.",
      "Rimuovi l'aglio e, usando un cucchiaio, crea quattro piccoli incavi nel sugo di pomodoro.",
      "Rompi un uovo all'interno di ciascun incavo, facendo attenzione a non rompere i tuorli.",
      "Copri immediatamente la padella con un coperchio e cuoci a fuoco basso per circa 4-5 minuti, finché l'albume non diventa bianco e sodo.",
      "Spegni il fuoco, cospargi la superficie con il parmigiano reggiano grattugiato, metti il coperchio ancora per 1 minuto per farlo fondere e servi con pane per la scarpetta.",
    ],
    tip: "Mantieni il fuoco al minimo dopo aver inserito le uova: il tuorlo deve rimanere liquido e cremoso all'interno, velato appena da una sottile pellicola bianca.",
    art: "/graphics/tomato.jpg",
    baseServings: 2,
  },
  {
    id: "involtini-prosciutto-ricotta",
    title: "Involtini di prosciutto crudo e ricotta alle erbe",
    description:
      "Un antipasto freddo senza cottura, rapido e sfizioso: morbide fette di prosciutto crudo che avvolgono una crema di ricotta leggera aromatizzata al pepe e formaggio.",
    minutes: 10,
    diet: "omnivore",
    tags: ["prosciutto crudo", "ricotta", "parmigiano"],
    ingredients: [
      "6 fette di prosciutto crudo non troppo sottili",
      "150 g di ricotta fresca",
      "2 cucchiai di parmigiano reggiano grattugiato",
      "1 cucchiaino di olio extravergine",
      "sale e pepe nero macinato fresco",
    ],
    steps: [
      "In una ciotola capiente unisci la ricotta fresca, il parmigiano reggiano grattugiato e il cucchiaino di olio extravergine.",
      "Lavora energicamente con una forchetta o una frusta a mano fino a ottenere una crema liscia, vellutata e priva di grumi.",
      "Regola di sale e aggiungi una generosa macinata di pepe nero secondo i tuoi gusti.",
      "Stendi le fette di prosciutto crudo su un tagliere pulito ben distese.",
      "Metti un cucchiaio abbondante di crema di ricotta all'estremità di ogni fetta di prosciutto.",
      "Arrotola delicatamente il prosciutto intorno al ripieno formando degli involtini cilindrici compatti e disponili su un piatto da portata.",
    ],
    tip: "Per una presentazione più ordinata puoi inserire la crema di ricotta in una sac-à-poche con beccuccio rigato prima di farcire le fette di prosciutto.",
    art: "/graphics/lettuce.jpg",
    baseServings: 2,
  },
  {
    id: "pasta-pomodorini-mozzarella",
    title: "Pasta veloce pomodorini e mozzarella filante",
    description:
      "Il primo piatto salvacena per eccellenza: una pasta corta saltata in padella con pomodori freschi e dadini di mozzarella che si sciolgono creando irresistibili fili.",
    minutes: 15,
    diet: "vegetarian",
    tags: ["pasta", "pomodori", "mozzarella", "aglio"],
    ingredients: [
      "160 g di pasta corta (penne o fusilli)",
      "2 pomodori ramati grandi (o pomodorini)",
      "125 g di mozzarella fresca",
      "1 spicchio d'aglio",
      "2 cucchiai di olio extravergine",
      "sale e pepe",
    ],
    steps: [
      "Porta a bollore una pentola di acqua salata e cuoci la pasta secondo i tempi indicati sulla confezione.",
      "Nel frattempo, lava i pomodori e tagliali a cubetti; taglia a cubetti anche la mozzarella e tienila da parte.",
      "In una padella capiente scalda l'olio extravergine con lo spicchio d'aglio intero; aggiungi i pomodori e salta a fuoco vivo per 3-4 minuti.",
      "Scola la pasta al dente (conservando un mestolo di acqua di cottura) e versala direttamente nella padella con i pomodori dopo aver rimosso l'aglio.",
      "Spegni il fuoco, aggiungi immediatamente i cubetti di mozzarella e mescola velocemente per farli scaldare e filare.",
      "Se necessario, unisci un goccio di acqua della pasta per legare il tutto e servi subito nei piatti.",
    ],
    tip: "Esegui l'ultimo passaggio rigorosamente a fuoco spento: il calore residuo della pasta è più che sufficiente per sciogliere la mozzarella senza farla aggregare in un unico blocco gommoso.",
    art: "/graphics/tomato.jpg",
    baseServings: 2,
  },
  {
    id: "crostini-salame-mozzarella",
    title: "Crostini caldi con salame e mozzarella",
    description:
      "Snack o antipasto espresso super filante: fette di pane ricoperte di mozzarella e fette di salame saporito, passate sotto il grill del forno fino a completa fusione.",
    minutes: 8,
    diet: "omnivore",
    tags: ["pane", "salame", "mozzarella"],
    ingredients: [
      "4 fette di pane (tipo baguette o pane casereccio)",
      "100 g di mozzarella",
      "8 fette di salame italiano",
      "1 cucchiaino di origano",
      "pepe nero",
    ],
    steps: [
      "Preriscalda il grill del forno alla massima potenza. Taglia la mozzarella a fette non troppo spesse.",
      "Disponi le fette di pane su una teglia foderata con carta da forno.",
      "Metti una o due fette di salame su ciascun pezzo di pane, adattandole alla dimensione della fetta.",
      "Copri il salame con le fette di mozzarella, facendo in modo che coprano bene la superficie.",
      "Spolvera con un pizzico di origano e una macinata leggera di pepe nero.",
      "Inforna la teglia nella parte più alta del forno per circa 4-5 minuti, finché la mozzarella non fa le bolle e accenna a dorarsi. Servi caldissimi.",
    ],
    tip: "Usa pane leggermente raffermo di un giorno: la cottura in forno lo renderà magnificamente croccante sotto lo strato morbido e filante del formaggio.",
    art: "/graphics/pepper.jpg",
    baseServings: 2,
  },
  {
    id: "zucchine-pomodori-parmigiano",
    title: "Zucchine e pomodori saltati al parmigiano",
    description:
      "Un contorno vegetariano leggero e colorato, saltato velocemente in padella per mantenere le verdure croccanti e completato da una ricca spolverata di parmigiano.",
    minutes: 15,
    diet: "vegetarian",
    tags: ["zucchine", "pomodori", "parmigiano", "aglio"],
    ingredients: [
      "2 zucchine medie",
      "2 pomodori maturi sodi",
      "2 cucchiai di parmigiano reggiano grattugiato",
      "1 spicchio d'aglio",
      "2 cucchiai di olio extravergine",
      "sale e pepe",
    ],
    steps: [
      "Lava le verdure; taglia le zucchine a mezzelune spesse e i pomodori a cubetti eliminando parte dei semi interni.",
      "In una padella antiaderente scalda l'olio extravergine con lo spicchio d'aglio schiacciato.",
      "Aggiungi le zucchine e saltale a fuoco vivace per circa 5-6 minuti, muovendo la padella finché non iniziano a prendere colore.",
      "Unisci i cubetti di pomodoro, regola di sale e pepe e continua la cottura per altri 3 minuti (i pomodori devono solo ammorbidirsi, non disfarsi).",
      "Elimina lo spicchio d'aglio e spegni il fuoco.",
      "Spolvera uniformemente con il parmigiano reggiano grattugiato, mescola delicatamente per distribuirlo e servi caldo o a temperatura ambiente.",
    ],
    tip: "Taglia le zucchine a pezzi di dimensioni uniformi per garantire una cottura omogenea e mantenerle piacevolmente sode sotto i denti.",
    art: "/graphics/onion.jpg",
    baseServings: 2,
  },
  {
    id: "crema-ricotta-dolce",
    title: "Crema di ricotta dolce veloce",
    description:
      "Un dessert al cucchiaio istantaneo e vellutato che unisce la delicatezza della ricotta alla dolcezza della marmellata. La soluzione perfetta quando si ha voglia di dolce senza accendere i fornelli.",
    minutes: 5,
    diet: "vegetarian",
    tags: ["ricotta", "marmellata", "dessert"],
    ingredients: [
      "200 g di ricotta fresca",
      "4 cucchiai di marmellata (gusto a scelta, es. fragole o frutti di bosco)",
      "1 pizzico di cannella in polvere",
    ],
    steps: [
      "Scola accuratamente la ricotta dal suo siero per renderla il più asciutta possibile.",
      "Trasferisci la ricotta in una ciotola, aggiungi un pizzico di cannella in polvere e lavorala energicamente con una frusta fino a ottenere una consistenza spumosa.",
      "Prendi due bicchieri o coppette da dessert pulite.",
      "Distribuisci la crema di ricotta sul fondo delle coppette livellando la superficie con un cucchiaio.",
      "Aggiungi due cucchiai generosi della tua marmellata preferita sopra lo strato di ricotta in ciascun bicchiere.",
      "Lascia riposare in frigorifero fino al momento di servire per una consistenza più soda e fresca.",
    ],
    tip: "Per ottenere una crema dalla consistenza finissima e setosa simile a una mousse, setaccia la ricotta facendola passare attraverso un colino a maglie strette prima di lavorarla.",
    art: "/graphics/lettuce.jpg",
    baseServings: 2,
  },
  {
    id: "rotolo-frittata-prosciutto-mozzarella",
    title: "Rotolo di frittata al prosciutto e mozzarella",
    description:
      "Una frittata sottile cotta in forno, farcita con prosciutto cotto e mozzarella e arrotolata su se stessa per creare girelle filanti spettacolari e golose.",
    minutes: 20,
    diet: "omnivore",
    tags: ["uova", "prosciutto cotto", "mozzarella", "parmigiano"],
    ingredients: [
      "4 uova medie",
      "100 g di mozzarella per pizza (asciutta)",
      "4 fette di prosciutto cotto",
      "2 cucchiai di parmigiano reggiano grattugiato",
      "sale e pepe",
    ],
    steps: [
      "In una ciotola sbatti le uova insieme al parmigiano reggiano, un pizzico di sale e una macinata di pepe nero.",
      "Fodera una teglia rettangolare piccola (circa 20x30 cm) con carta da forno bagnata e strizzata; versa il composto di uova livellandolo bene.",
      "Cuoci in forno preriscaldato a 180°C per circa 10-12 minuti, finché l'uovo non si sarà completamente rappreso.",
      "Sforna la frittata e, mentre è ancora calda, disponi sulla superficie le fette di prosciutto cotto e la mozzarella tagliata a fette sottilissime.",
      "Aiutandoti con la carta da forno sottostante, arrotola la frittata strettamente partendo dal lato più corto formando un cilindro.",
      "Avvolgi il rotolo nella carta forno e rimettilo nel forno spento ma ancora caldo per 3 minuti per far fondere la mozzarella, poi taglia a fette e servi.",
    ],
    tip: "Usa una mozzarella specifica per pizza o lasciata scolare per ore: una mozzarella troppo acquosa rilascerebbe liquidi rovinando la compattezza del rotolo.",
    art: "/graphics/onion.jpg",
    baseServings: 2,
  },
  {
    id: "rustico-salame-ricotta",
    title: "Rustico svuotafrigo salame e ricotta",
    description:
      "Una torta salata veloce senza sfoglia: un impasto morbido a base di uova, ricotta e parmigiano arricchito da pezzetti di salame che creano un tortino fragrante.",
    minutes: 30,
    diet: "omnivore",
    tags: ["uova", "ricotta", "salame", "parmigiano"],
    ingredients: [
      "3 uova medie",
      "200 g di ricotta fresca",
      "60 g di salame italiano",
      "4 cucchiai di parmigiano reggiano grattugiato",
      "1 cucchiaino di burro (per la teglia)",
      "sale e pepe",
    ],
    steps: [
      "In una ciotola lavora la ricotta con la forchetta fino a renderla cremosa e morbida. Taglia il salame a piccoli cubetti.",
      "Aggiungi le uova una alla volta alla ricotta, incorporandole bene prima di inserire la successiva.",
      "Unisci al composto il parmigiano reggiano grattugiato, i cubetti di salame e un pizzico di sale e pepe nero.",
      "Mescola bene il tutto con un cucchiaio di legno fino a ottenere un impasto omogeneo.",
      "Imburra una pirofila da forno da 20 cm di diametro e versa il composto livellando la superficie.",
      "Cuoci in forno preriscaldato a 180°C per circa 20-25 minuti, fino a quando il rustico risulterà gonfio, sodo al tatto e dorato in superficie.",
    ],
    tip: "Per verificare la cottura interna del rustico usa lo stecchino: inserito al centro del tortino deve uscire asciutto e pulito.",
    art: "/graphics/pepper.jpg",
    baseServings: 2,
  },
  {
    id: "involtini-zucchine-prosciutto-crudo",
    title: "Involtini di zucchine grigliate e prosciutto crudo",
    description:
      "Finger food fresco e leggero: sottili fette di zucchine grigliate arrotolate attorno a un ripieno saporito di prosciutto crudo e scaglie di parmigiano reggiano.",
    minutes: 15,
    diet: "omnivore",
    tags: ["zucchine", "prosciutto crudo", "parmigiano"],
    ingredients: [
      "2 zucchine lunghe e dritte",
      "6 fette di prosciutto crudo",
      "30 g di parmigiano reggiano in scaglie",
      "1 cucchiaio di olio extravergine",
      "sale e pepe",
    ],
    steps: [
      "Lava le zucchine e tagliale nel senso della lunghezza a fette sottili circa 3 millimetri usando una mandolina o un coltello affilato.",
      "Scalda una piastra di ghisa e griglia le fette di zucchina per circa 2 minuti per lato; disponile su un piatto e lasciale raffreddare.",
      "Condisci leggermente le zucchine fredde con un pizzico di sale e una goccia di olio extravergine.",
      "Posiziona mezza fetta di prosciutto crudo sopra ogni fetta di zucchina grigliata.",
      "Aggiungi alcune scaglie di parmigiano reggiano sopra il prosciutto a una delle estremità.",
      "Arrotola la zucchina partendo dall'estremità con il formaggio formando un involtino e fissalo, se serve, con uno stuzzicadenti.",
    ],
    tip: "Non salare eccessivamente le zucchine durante la grigliatura poiché il prosciutto crudo e il parmigiano reggiano conferiranno già una forte nota sapida al piatto.",
    art: "/graphics/onion.jpg",
    baseServings: 2,
  },
  {
    id: "uova-strapazzate-parmigiano",
    title: "Uova strapazzate cremose al burro e parmigiano",
    description:
      "Le classiche uova della colazione o di un pranzo veloce, cotte a fuoco dolcissimo con burro e arricchite alla fine da parmigiano per una consistenza vellutata.",
    minutes: 8,
    diet: "vegetarian",
    tags: ["uova", "burro", "parmigiano"],
    ingredients: [
      "2 uova medie",
      "15 g di burro",
      "2 cucchiai di parmigiano reggiano grattugiato",
      "sale e pepe nero",
    ],
    steps: [
      "Rompi le uova in una ciotola, aggiungi un pizzico di sale e pepe e sbattile leggermente con una forchetta per soli 10 secondi.",
      "Sciogli il burro in una padella antiaderente piccola a fuoco medio-basso, facendo attenzione a non farlo friggere o scurire.",
      "Versa le uova nella padella e abbassa immediatamente il fuoco al minimo.",
      "Usando una spatola di silicone, mescola continuamente il composto raschiando il fondo e i bordi man mano che l'uovo inizia a rapprendersi.",
      "Quando le uova sono ancora molto morbide, lucide e cremose (dopo circa 3-4 minuti), spegni il fuoco e allontana la padella dal calore.",
      "Aggiungi subito il parmigiano reggiano grattugiato, mescola un'ultima volta per amalgamare e servi immediatamente sul piatto.",
    ],
    tip: "Il segreto per la perfetta cremosità risiede nel controllo del calore: se vedi che le uova si rapprendono troppo in fretta, solleva la padella dal fuoco per qualche secondo continuando a mescolare.",
    art: "/graphics/lemon.jpg",
    baseServings: 1,
  },
  {
    id: "zucchine-trifolate",
    title: "Zucchine trifolate veloci in padella",
    description:
      "Il contorno passe-partout della cucina di casa: rondelle sottili di zucchina saltate in padella con aglio e olio, portate a cottura veloce per preservarne la brillantezza.",
    minutes: 12,
    diet: "vegan",
    tags: ["zucchine", "aglio", "olio"],
    ingredients: [
      "3 zucchine medie",
      "1 spicchio d'aglio",
      "2 cucchiai di olio extravergine",
      "sale e pepe",
    ],
    steps: [
      "Lava le zucchine, spuntale e tagliale a rondelle regolari non troppo spesse (circa 4-5 millimetri).",
      "In una padella ampia versa l'olio extravergine e aggiungi lo spicchio d'aglio sbucciato e schiacciato.",
      "Scalda a fuoco medio finché l'aglio non rilascia il suo profumo, quindi unisci tutte le zucchine in un solo colpo.",
      "Salta le zucchine a fuoco vivace per 5 minuti senza coprire, girandole delicatamente per non romperle.",
      "Abbassa la fiamma, regola di sale e pepe e continua la cottura per altri 3-4 minuti finché non risultano tenere ma ancora sode al cuore.",
      "Elimina lo spicchio d'aglio prima di trasferire le verdure nel piatto da portata.",
    ],
    tip: "Evita di coprire la padella con un coperchio durante i primi minuti di cottura: il vapore intrappolato farebbe bollire le zucchine rendendole molli invece che dorate e croccanti.",
    art: "/graphics/onion.jpg",
    baseServings: 2,
  },
  {
    id: "crostini-prosciutto-burro",
    title: "Crostini rustici al prosciutto crudo e burro",
    description:
      "L'antipasto vintage che non passa mai di moda: fette di pane tostate calde sulle quali il burro si scioglie leggermente, sormontate da prosciutto crudo di alta qualità.",
    minutes: 5,
    diet: "omnivore",
    tags: ["pane", "prosciutto crudo", "burro"],
    ingredients: [
      "4 fette di pane casereccio",
      "4 fette di prosciutto crudo",
      "20 g di burro di ottima qualità",
      "pepe nero in grani",
    ],
    steps: [
      "Tosta le fette di pane su una piastra rovente o nel tostapane per circa 2 minuti per lato fino a renderle croccanti all'esterno.",
      "Togli il burro dal frigorifero qualche minuto prima in modo che sia facilmente spalmabile ma ancora sodo.",
      "Spalma un velo generoso di burro sulla superficie delle fette di pane calde, lasciando che penetri leggermente nella mollica.",
      "Adagia una fetta di prosciutto crudo sopra il burro su ciascun crostino, ripiegandola morbidamente per dare volume.",
      "Rifinisci a piacere con una rotazione leggera di mulinello di pepe nero macinato fresco. Servi immediatamente.",
    ],
    tip: "Usa un burro di centrifuga di alta qualità o un burro salato per esaltare al massimo il contrasto dolce-sapido con il prosciutto crudo.",
    art: "/graphics/lettuce.jpg",
    baseServings: 2,
  },
  {
    id: "pomodori-gratinati-parmigiano",
    title: "Pomodori gratinati saporiti al parmigiano",
    description:
      "Metà pomodori carnosi ricoperti da una ricca panatura aromatica di parmigiano reggiano e olio, cotti al forno fino a ottenere una crosticina croccante.",
    minutes: 25,
    diet: "vegetarian",
    tags: ["pomodori", "parmigiano", "aglio"],
    ingredients: [
      "2 pomodori ramati grandi e sodi",
      "4 cucchiai di parmigiano reggiano grattugiato",
      "1 spicchio d'aglio tritato finissimo (opzionale)",
      "2 cucchiai di olio extravergine",
      "sale, pepe e origano",
    ],
    steps: [
      "Lava i pomodori e tagliali a metà in senso orizzontale. Elimina delicatamente parte dell'acqua di vegetazione e dei semi interni.",
      "Disponi le quattro metà di pomodoro su una teglia rivestita di carta da forno con la parte tagliata rivolta verso l'alto.",
      "Sala leggermente la superficie dei pomodori per favorire la perdita di liquidi in cottura.",
      "In una ciotolina unisci il parmigiano reggiano, l'aglio tritato, l'origano e un pizzico di pepe nero.",
      "Distribuisci il mix di formaggio e aromi in modo uniforme sopra ogni metà di pomodoro creando uno strato compatto.",
      "Irrora con un filo d'olio extravergine e inforna a 190°C per 20 minuti fino a completa doratura dello strato superiore.",
    ],
    tip: "Se preferisci una crosticina ancora più spessa e rustica, puoi miscelare il parmigiano reggiano con un cucchiaio di pangrattato prima di cospargere i pomodori.",
    art: "/graphics/tomato.jpg",
    baseServings: 2,
  },
  {
    id: "rustico-zucchine-mozzarella",
    title: "Rustico filante zucchine e mozzarella",
    description:
      "Un tortino da cuocere in padella o al forno, composto da uova e zucchine grattugiate che racchiudono un cuore filante e goloso di mozzarella fusa.",
    minutes: 25,
    diet: "vegetarian",
    tags: ["uova", "zucchine", "mozzarella", "parmigiano"],
    ingredients: [
      "3 uova medie",
      "2 zucchine medie",
      "100 g di mozzarella ben sgocciolata",
      "3 cucchiai di parmigiano reggiano grattugiato",
      "1 cucchiaio di olio extravergine",
      "sale e pepe",
    ],
    steps: [
      "Lava le zucchine e grattugiale usando una grattugia a fori larghi. Strizzale con le mani per eliminare il liquido in eccesso.",
      "In una ciotola sbatti le uova con il parmigiano reggiano, sale e pepe nero. Unisci le zucchine grattugiate e mescola bene.",
      "Scalda l'olio extravergine in una padella antiaderente da 20 cm e versa la metà del composto di uova e zucchine.",
      "Distribuisci sopra la mozzarella tagliata a dadini piccoli, mantenendoti leggermente lontana dai bordi esterni.",
      "Copri la mozzarella con il restante composto di uova e zucchine livellando bene con il dorso di un cucchiaio.",
      "Cuoci a fuoco basso con coperchio per 6-7 minuti, poi gira delicatamente il rustico e cuoci per altri 5 minuti dall'altro lato fino a cottura completa.",
    ],
    tip: "Per girare il rustico in totale sicurezza senza romperlo, fallo scivolare su un piatto piano grande, capovolgi la padella sopra il piatto e rigira con un movimento deciso.",
    art: "/graphics/onion.jpg",
    baseServings: 2,
  },
];
