import type { Recipe } from "./types";

type BookRecipe = Omit<Recipe, "missing" | "servings"> & {
  tags: string[];
  baseServings: number;
};

/** Secondi di carne e pesce per il ricettario classico. */
export const RECIPES_SECONDI: BookRecipe[] = [
  // —— Carne ——
  {
    id: "tacchino-pizzaiola-mozzarella",
    title: "Tacchino alla pizzaiola con mozzarella",
    description:
      "Un secondo veloce e filante che unisce la leggerezza del tacchino al gusto mediterraneo del pomodoro e della mozzarella.",
    minutes: 20,
    diet: "omnivore",
    tags: ["tacchino", "mozzarella", "pomodori", "aglio"],
    ingredients: [
      "300 g di fesa di tacchino a fette",
      "125 g di mozzarella",
      "150 g di passata di pomodoro",
      "1 spicchio d'aglio",
      "2 cucchiai di olio extravergine d'oliva",
      "origano secco q.b.",
      "sale e pepe",
    ],
    steps: [
      "Scalda l'olio in una padella capiente insieme allo spicchio d'aglio schiacciato.",
      "Adagia le fette di tacchino e rosolale per 2 minuti su entrambi i lati.",
      "Versa la passata di pomodoro sulle fette, regola di sale, pepe e origano, poi copri con un coperchio e cuoci a fuoco medio per 8 minuti.",
      "Taglia la mozzarella a fette e posizionala sopra la carne. Copri nuovamente per 2 minuti fino a quando non sarà completamente fusa.",
    ],
    tip: "Asciuga bene la mozzarella prima di metterla in padella per evitare che rilasci troppa acqua nel sugo.",
    art: "/graphics/tomato.jpg",
    baseServings: 2,
  },
  {
    id: "hamburger-cipolle-caramellate",
    title: "Hamburger gourmet con cipolle caramellate",
    description:
      "Il classico hamburger casalingo arricchito da cipolle dolci e morbide per un contrasto di sapori irresistibile.",
    minutes: 25,
    diet: "omnivore",
    tags: ["hamburger", "manzo", "cipolla"],
    ingredients: [
      "2 hamburger di manzo (circa 150 g l'uno)",
      "1 cipolla rossa grande",
      "1 cucchiaio di zucchero di canna",
      "2 cucchiai di aceto balsamico",
      "2 cucchiai di olio extravergine d'oliva",
      "sale e pepe",
    ],
    steps: [
      "Affetta la cipolla finemente e lasciala appassire in padella con l'olio e un goccio d'acqua per circa 10 minuti.",
      "Aggiungi lo zucchero di canna e l'aceto balsamico alle cipolle, mescola bene e lascia caramellare a fuoco basso per altri 5 minuti.",
      "Scalda una piastra o una padella antiaderente e cuoci gli hamburger per circa 3-4 minuti per lato, regolando di sale e pepe.",
      "Impiatta l'hamburger ben caldo coprendolo generosamente con le cipolle caramellate.",
    ],
    tip: "Non schiacciare mai l'hamburger con la paletta durante la cottura per non far uscire i succhi della carne.",
    art: "/graphics/onion.jpg",
    baseServings: 2,
  },
  {
    id: "macinato-zucchine-carote",
    title: "Macinato di manzo saltato con zucchine e carote",
    description:
      "Un piatto unico espresso, leggero e ricco di verdure, perfetto per una cena dell'ultimo minuto.",
    minutes: 20,
    diet: "omnivore",
    tags: ["carne macinata", "zucchine", "carote", "cipolla"],
    ingredients: [
      "300 g di macinato di manzo",
      "1 zucchina grande",
      "1 carota",
      "1/2 cipolla bianca",
      "2 cucchiai di olio extravergine d'oliva",
      "2 cucchiai di salsa di soia (opzionale)",
      "sale e pepe",
    ],
    steps: [
      "Trita la cipolla e taglia la zucchina e la carota a listarelle sottili o a julienne.",
      "In una padella capiente o un wok, scalda l'olio e fai appassire la cipolla. Aggiungi il macinato e sgranalo bene con un cucchiaio di legno mentre cuoce per 5 minuti.",
      "Unisci le zucchine e le carote, regola di sale e pepe e salta a fuoco vivo per altri 7-8 minuti, mantenendo le verdure croccanti.",
      "Sfuma con la salsa di soia negli ultimi 30 secondi di cottura prima di servire.",
    ],
    tip: "Taglia le verdure della stessa dimensione per garantire una cottura uniforme e veloce.",
    art: "/graphics/onion.jpg",
    baseServings: 2,
  },
  {
    id: "vitello-milanese",
    title: "Fettine di vitello fritte alla milanese",
    description:
      "La cotoletta dorata e croccante amata da grandi e bambini, preparata secondo la tradizione casalinga.",
    minutes: 20,
    diet: "omnivore",
    tags: ["vitello", "uova", "pangrattato", "burro"],
    ingredients: [
      "4 fettine di vitello sottili",
      "2 uova",
      "150 g di pangrattato",
      "50 g di burro (o olio di semi per friggere)",
      "sale",
      "1 limone (per servire)",
    ],
    steps: [
      "Batti leggermente le fettine di vitello con un batticarne per renderle uniformi e pratica dei piccoli tagli sui bordi per non farle arricciare.",
      "Sbatti le uova in un piatto fondo con un pizzico di sale. Metti il pangrattato in un altro piatto capiente.",
      "Passa ogni fettina prima nell'uovo sbattuto e poi nel pangrattato, premendo bene con le dita per farlo aderire perfettamente.",
      "Sciogli il burro in padella e friggi le fettine per circa 3 minuti per lato fino a doratura. Asciugale su carta assorbente e servile calde con spicchi di limone.",
    ],
    tip: "Per una panatura ancora più croccante, puoi fare un doppio passaggio nell'uovo e nel pangrattato.",
    art: "/graphics/lemon.jpg",
    baseServings: 2,
  },
  {
    id: "braciole-maiale-erbe",
    title: "Braciole di maiale alla griglia marinate alle erbe",
    description:
      "Un secondo saporito e succulento grazie a una marinatura veloce che ammorbidisce la carne di maiale.",
    minutes: 25,
    diet: "omnivore",
    tags: ["maiale", "rosmarino", "salvia", "limone"],
    ingredients: [
      "2 braciole di maiale",
      "1 rametto di rosmarino",
      "2 foglie di salvia",
      "1 spicchio d'aglio",
      "succo di 1/2 limone",
      "3 cucchiai di olio extravergine d'oliva",
      "sale e pepe in grani",
    ],
    steps: [
      "Prepara una marinatura unendo in una pirofila l'olio, il succo di limone, lo spicchio d'aglio schiacciato, il rosmarino e la salvia tritati.",
      "Immergi le braciole di maiale nella marinatura, rigirale bene e lasciale riposare a temperatura ambiente per 10 minuti.",
      "Scalda una piastra in ghisa o una griglia sul fuoco. Quando è rovente, cuoci le braciole per circa 5-6 minuti per lato.",
      "Regola di sale e pepe nero macinato fresco solo a fine cottura prima di impiattare.",
    ],
    tip: "Lascia riposare le braciole cotte su un tagliere per 2 minuti prima di servirle per ridistribuire i succhi.",
    art: "/graphics/lemon.jpg",
    baseServings: 2,
  },
  {
    id: "involtini-manzo-prosciutto-formaggio",
    title: "Involtini di fettine di manzo con prosciutto e formaggio",
    description:
      "I classici involtini della nonna, ripieni e cotti in un saporito sughetto al vino bianco.",
    minutes: 25,
    diet: "omnivore",
    tags: ["manzo", "prosciutto cotto", "formaggio", "vino bianco"],
    ingredients: [
      "4 fettine di manzo sottili",
      "4 fette di prosciutto cotto",
      "4 fette di formaggio dolce (tipo provola o edamer)",
      "1/2 bicchiere di vino bianco secco",
      "2 cucchiai di olio extravergine d'oliva",
      "1 foglia di salvia",
      "sale e pepe",
    ],
    steps: [
      "Stendi le fettine di manzo su un piano di lavoro, regola leggermente di sale e pepe.",
      "Adagia su ogni fettina una fetta di prosciutto cotto e una di formaggio.",
      "Arrotola la carne strettamente su se stessa per formare l'involtino e blocca le estremità con degli stuzzicadenti.",
      "Scalda l'olio con la salvia in padella, dora gli involtini per 3 minuti, sfuma con il vino bianco e lascia cuocere coperto a fuoco basso per 12 minuti.",
    ],
    tip: "Fai sfumare completamente l'alcol del vino a fiamma alta prima di abbassare il fuoco e coprire.",
    art: "/graphics/pepper.jpg",
    baseServings: 2,
  },
  {
    id: "bistecca-burro-aromatico",
    title: "Bistecca di manzo al burro aromatico e aglio",
    description:
      "Una cottura in stile steakhouse per valorizzare al massimo una buona fetta di carne con aromi semplici.",
    minutes: 15,
    diet: "omnivore",
    tags: ["manzo", "burro", "aglio", "rosmarino"],
    ingredients: [
      "2 bistecche di manzo (controfiletto o costata)",
      "30 g di burro",
      "2 spicchi d'aglio",
      "1 rametto di rosmarino",
      "1 cucchiaio di olio extravergine d'oliva",
      "sale grosso e pepe nero",
    ],
    steps: [
      "Tira fuori la carne dal frigo almeno 20 minuti prima di cuocerla e asciugala bene con carta da cucina.",
      "Scalda l'olio in una padella dal fondo spesso a fiamma alta. Quando scotta, cuoci le bistecche per 2-3 minuti per lato senza muoverle.",
      "Abbassa leggermente la fiamma, aggiungi il burro, gli spicchi d'aglio schiacciati in camicia e il rosmarino nella padella.",
      "Inclina la padella e, usando un cucchiaio, irrora continuamente la carne con il burro fuso spumeggiante per un altro minuto. Regola di sale grosso e pepe.",
    ],
    tip: "Non bucare mai la carne con una forchetta per girarla, usa sempre delle pinze da cucina.",
    art: "/graphics/onion.jpg",
    baseServings: 2,
  },
  {
    id: "polpette-insalata-sfiziosa",
    title: "Polpette di carne fredde in insalata sfiziosa",
    description:
      "Il modo perfetto per trasformare le polpette avanzate del giorno prima in un secondo piatto estivo e fresco.",
    minutes: 15,
    diet: "omnivore",
    tags: ["polpette", "pomodorini", "olive", "cipolla"],
    ingredients: [
      "8-10 polpette di carne già cotte",
      "100 g di pomodorini",
      "1/2 cipolla rossa (opzionale)",
      "50 g di olive nere snocciolate",
      "3 cucchiai di olio extravergine d'oliva",
      "origano secco q.b.",
      "sale",
    ],
    steps: [
      "Prendi le polpette avanzate fredde di frigorifero e tagliale a metà o in quattro parti a seconda della dimensione.",
      "Lava i pomodorini e tagliali in quattro. Affetta la cipolla rossa molto sottilmente.",
      "Riunisci in una ciotola le polpette, i pomodorini, la cipolla e le olive nere.",
      "Condisci il tutto con l'olio extravergine d'oliva, un pizzico di sale e abbondante origano, poi mescola delicatamente.",
    ],
    tip: "Puoi arricchire l'insalata aggiungendo dei cubetti di formaggio primosale o della rucola fresca.",
    art: "/graphics/tomato.jpg",
    baseServings: 2,
  },
  {
    id: "pollo-limone-capperi",
    title: "Petto di pollo al limone e capperi in padella",
    description:
      "Un grande classico salvacena, cremoso e dal tocco aspro e sapido che trasforma il petto di pollo.",
    minutes: 15,
    diet: "omnivore",
    tags: ["pollo", "limone", "capperi"],
    ingredients: [
      "300 g di petto di pollo a fette",
      "succo di 1 limone",
      "1 cucchiaio di capperi sotto sale",
      "2 cucchiai di farina 00",
      "2 cucchiai di olio extravergine d'oliva",
      "1/2 bicchiere di brodo vegetale o acqua",
      "sale e prezzemolo",
    ],
    steps: [
      "Passa le fettine di petto di pollo nella farina da entrambi i lati, scrollando l'eccesso.",
      "Sciacqua i capperi per eliminare il sale in eccesso. Scalda l'olio in una padella e unisci il pollo, facendolo dorare 2 minuti per lato.",
      "Versa il succo di limone e il brodo (o l'acqua), aggiungi i capperi e un pizzico di sale.",
      "Lascia restringere il liquido a fuoco medio per 5 minuti fino a formare una cremina. Spolvera di prezzemolo tritato.",
    ],
    tip: "Se la cremina si asciuga troppo velocemente, aggiungi un altro goccio d'acqua calda o brodo.",
    art: "/graphics/lemon.jpg",
    baseServings: 2,
  },
  {
    id: "wurstel-uova-tegamino",
    title: "Padellata svuotafrigo di wurstel e uova al tegamino",
    description:
      "Una ricetta super express ed economica che risolve il pasto con quello che si trova spesso nel frigo.",
    minutes: 10,
    diet: "omnivore",
    tags: ["wurstel", "uova", "cipolla"],
    ingredients: [
      "3 wurstel grandi",
      "2 uova",
      "1/2 cipolla bianca",
      "2 cucchiai di olio extravergine d'oliva",
      "sale e pepe",
    ],
    steps: [
      "Taglia i wurstel a rondelle non troppo sottili e trita finemente la cipolla.",
      "In una padella antiaderente, scalda l'olio e fai dorare la cipolla per un minuto. Aggiungi i wurstel e saltali per 4 minuti finché non saranno leggermente croccanti.",
      "Distanzia i wurstel creando due piccoli spazi vuoti nella padella e rompi un uovo in ciascuno spazio.",
      "Metti il coperchio e cuoci a fuoco basso per 3-4 minuti, finché l'albume non sarà bianco e sodo, mantenendo il tuorlo morbido. Regola di sale e pepe.",
    ],
    tip: "Accompagna questo piatto con dei crostini di pane tostato per fare la scarpetta con l'uovo.",
    art: "/graphics/onion.jpg",
    baseServings: 2,
  },
  // —— Pesce ——
  {
    id: "calamari-olive-capperi",
    title: "Calamari saltati in padella con olive e capperi",
    description:
      "Calamari teneri e saporiti cucinati in pochissimo tempo con i profumi tipici della cucina mediterranea.",
    minutes: 15,
    diet: "omnivore",
    tags: ["calamari", "pomodorini", "olive", "capperi"],
    ingredients: [
      "400 g di calamari puliti",
      "10 pomodorini",
      "1 cucchiaio di capperi sotto sale",
      "10 olive nere",
      "1 spicchio d'aglio",
      "3 cucchiai di olio extravergine d'oliva",
      "1/2 bicchiere di vino bianco",
      "sale e peperoncino",
    ],
    steps: [
      "Taglia i tubi dei calamari a rondelle e lascia i tentacoli interi. Sciacqua i capperi.",
      "In una padella scalda l'olio con l'aglio e un pizzico di peperoncino. Aggiungi i calamari e salta a fuoco vivo per 2 minuti.",
      "Sfuma con il vino bianco e lascia evaporare l'alcol per un minuto, poi aggiungi i pomodorini tagliati a metà, le olive e i capperi.",
      "Abbassa la fiamma e cuoci per altri 8 minuti. Regola di sale solo alla fine.",
    ],
    tip: "Non prolungare la cottura dei calamari oltre i tempi indicati, altrimenti diventeranno duri e gommosi.",
    art: "/graphics/tomato.jpg",
    baseServings: 2,
  },
  {
    id: "seppie-umido-piselli",
    title: "Seppie in umido con piselli surgelati",
    description:
      "Un grande classico della cucina di casa, morbido e perfetto da gustare con fette di pane abbrustolito.",
    minutes: 35,
    diet: "omnivore",
    tags: ["seppie", "piselli", "pomodori", "cipolla"],
    ingredients: [
      "400 g di seppie pulite",
      "200 g di piselli (freschi o surgelati)",
      "200 g di passata di pomodoro",
      "1/2 cipolla bianca",
      "1/2 bicchiere di vino bianco",
      "2 cucchiai di olio extravergine d'oliva",
      "sale e prezzemolo",
    ],
    steps: [
      "Taglia le seppie a striscioline o a cubetti. Trita la cipolla.",
      "In un tegame scalda l'olio e fai appassire la cipolla. Unisci le seppie e rosolale per 3 minuti.",
      "Sfuma con il vino bianco. Quando è evaporato, unisci la passata di pomodoro e i piselli.",
      "Copri con il coperchio, abbassa la fiamma e lascia cuocere per circa 25 minuti fino a quando le seppie saranno tenere. Regola di sale e spolvera di prezzemolo.",
    ],
    tip: "Se il sugo dovesse restringersi troppo durante la cottura, aggiungi un mestolo di acqua calda.",
    art: "/graphics/tomato.jpg",
    baseServings: 2,
  },
  {
    id: "zuppetta-cozze-vongole",
    title: "Zuppetta veloce di cozze e vongole al pomodoro",
    description:
      "Il profumo del mare in tavola con un sauté rapido arricchito da pomodorini freschi e tanto aglio.",
    minutes: 20,
    diet: "omnivore",
    tags: ["cozze", "vongole", "pomodorini", "aglio"],
    ingredients: [
      "400 g di cozze già pulite",
      "400 g di vongole già spurgate",
      "150 g di pomodorini o polpa di pomodoro",
      "2 spicchi d'aglio",
      "1/2 bicchiere di vino bianco",
      "3 cucchiai di olio extravergine d'oliva",
      "prezzemolo fresco q.b.",
      "peperoncino q.b.",
    ],
    steps: [
      "In una pentola capiente scalda l'olio con gli spicchi d'aglio schiacciati e il peperoncino.",
      "Aggiungi i pomodorini tagliati a pezzetti e falli saltare per 3 minuti.",
      "Unisci le cozze e le vongole alla pentola, versa il vino bianco e copri immediatamente con il coperchio.",
      "Cuoci a fiamma viva per 5-6 minuti scuotendo la pentola di tanto in tanto. Spegni il fuoco non appena tutti i gusci si saranno aperti e cospargi con il prezzemolo tritato.",
    ],
    tip: "Scarta sempre i frutti di mare che rimangono chiusi dopo la cottura.",
    art: "/graphics/tomato.jpg",
    baseServings: 2,
  },
  {
    id: "sardine-limone-pangrattato",
    title: "Sardine al limone e pangrattato in padella",
    description:
      "Un secondo di pesce azzurro economico, ricco di omega-3 e saporito grazie alla panatura aromatica.",
    minutes: 15,
    diet: "omnivore",
    tags: ["sardine", "limone", "pangrattato", "aglio"],
    ingredients: [
      "300 g di sardine fresche pulite e aperte a libro",
      "4 cucchiai di pangrattato",
      "scorza grattugiata di 1 limone",
      "1 spicchio d'aglio tritato",
      "3 cucchiai di olio extravergine d'oliva",
      "sale e prezzemolo",
    ],
    steps: [
      "Mescola in una ciotola il pangrattato con la scorza di limone, il prezzemolo tritato, l'aglio e un pizzico di sale.",
      "Passa le sardine aperte nel mix di pangrattato facendolo aderire bene alla polpa.",
      "Scalda l'olio in una padella antiaderente capiente.",
      "Adagia le sardine e cuocile a fuoco medio-alto per 2-3 minuti per lato fino a quando la panatura sarà dorata e croccante.",
    ],
    tip: "Maneggia le sardine con cura per evitare di romperle durante la girata in padella.",
    art: "/graphics/lemon.jpg",
    baseServings: 2,
  },
  {
    id: "involtini-pesce-spada-siciliana",
    title: "Involtini di pesce spada con ripieno alla siciliana",
    description:
      "Bocconcini succosi di pesce spada ripieni di sapori tipici del sud, veloci da cuocere sul fuoco.",
    minutes: 20,
    diet: "omnivore",
    tags: ["pesce spada", "pangrattato", "capperi", "parmigiano"],
    ingredients: [
      "4 fettine sottili di pesce spada (circa 250 g totali)",
      "3 cucchiai di pangrattato",
      "1 cucchiaio di parmigiano grattugiato",
      "1 cucchiaio di capperi tritati",
      "2 cucchiai di olio extravergine d'oliva",
      "sale e pepe",
    ],
    steps: [
      "Prepara il ripieno unendo in una ciotola il pangrattato, il parmigiano, i capperi tritati, un cucchiaio d'olio, sale e pepe.",
      "Distribuisci il ripieno al centro di ogni fettina di pesce spada.",
      "Arrotola le fettine per formare degli involtini e fermali con degli stuzzicadenti.",
      "Scalda un cucchiaio d'olio in una padella e cuoci gli involtini a fuoco medio per circa 3 minuti per lato, finché non saranno opachi e dorati.",
    ],
    tip: "Puoi aggiungere un pizzico di uvetta e pinoli al ripieno per un sapore ancora più autentico.",
    art: "/graphics/lemon.jpg",
    baseServings: 2,
  },
  {
    id: "polpo-insalata-patate",
    title: "Polpo all'insalata tiepida con patate e prezzemolo",
    description:
      "Un abbinamento intramontabile, perfetto da servire tiepido come secondo piatto leggero.",
    minutes: 40,
    diet: "omnivore",
    tags: ["polpo", "patate", "limone", "prezzemolo"],
    ingredients: [
      "500 g di polpo (fresco o decongelato)",
      "2 patate medie",
      "succo di 1/2 limone",
      "3 cucchiai di olio extravergine d'oliva",
      "1 spicchio d'aglio (opzionale)",
      "sale e prezzemolo tritato",
    ],
    steps: [
      "Sbuccia le patate, tagliale a cubetti e lessale in acqua salata per circa 15 minuti finché non saranno tenere ma sode.",
      "Cuoci il polpo in acqua bollente per circa 30 minuti. Lascialo intiepidire nella sua acqua di cottura prima di scolarlo e tagliarlo a pezzetti.",
      "Riunisci in una ciotola i cubetti di patate e i pezzetti di polpo.",
      "Condisci con l'olio extravergine d'oliva, il succo di limone, l'aglio intero (da togliere dopo), sale e abbondante prezzemolo tritato.",
    ],
    tip: "Per rendere il polpo fresco più tenero, congelalo per 24 ore prima di cucinarlo per rompere le fibre delle carni.",
    art: "/graphics/lettuce.jpg",
    baseServings: 2,
  },
  {
    id: "trota-crosta-patate",
    title: "Filetti di trota salmonata in crosta di patate",
    description:
      "Un modo elegante e saporito per cucinare la trota, coprendola con sfoglie croccanti di patate.",
    minutes: 20,
    diet: "omnivore",
    tags: ["trota", "patate", "rosmarino"],
    ingredients: [
      "2 filetti di trota salmonata (senza lische)",
      "1 patata grande",
      "2 cucchiai di olio extravergine d'oliva",
      "1 rametto di rosmarino",
      "sale e pepe",
    ],
    steps: [
      "Sbuccia la patata e tagliala a fettine sottilissime, preferibilmente usando una mandolina.",
      "Adagia i filetti di trota con la pelle rivolta verso il basso in una padella antiaderente unta d'olio. Regola di sale e pepe.",
      "Copri la superficie della polpa del pesce con le fettine di patata sovrapponendole leggermente come se fossero squame.",
      "Copri con un coperchio e cuoci a fuoco medio per 10 minuti, poi gira delicatamente il filetto dal lato delle patate e cuoci scoperto a fiamma alta per altri 5 minuti fino a renderle croccanti.",
    ],
    tip: "Asciuga bene le fettine di patata con un canovaccio prima di metterle sul pesce per renderle più croccanti.",
    art: "/graphics/onion.jpg",
    baseServings: 2,
  },
  {
    id: "sgombro-cipolle-agrodolce",
    title: "Sgombro in padella con cipolle rosse in agrodolce",
    description:
      "Il sapore deciso dello sgombro viene bilanciato dalla dolcezza delle cipolle rosse sfumate con l'aceto.",
    minutes: 20,
    diet: "omnivore",
    tags: ["sgombro", "cipolla", "aceto"],
    ingredients: [
      "2 filetti di sgombro fresco",
      "2 cipolle rosse",
      "1 cucchiaio di zucchero",
      "3 cucchiai di aceto di vino bianco",
      "2 cucchiai di olio extravergine d'oliva",
      "sale",
    ],
    steps: [
      "Affetta le cipolle rosse e cuocile in padella con l'olio e un pizzico di sale per 10 minuti a fuoco basso finché non saranno morbide.",
      "Aggiungi lo zucchero e l'aceto alle cipolle, alza la fiamma e lascia sfumare per 2 minuti fino ad ottenere l'effetto agrodolce. Rimuovi le cipolle dalla padella.",
      "Nella stessa padella, adagia i filetti di sgombro dal lato della pelle e cuocili per 4 minuti.",
      "Gira i filetti, unisci nuovamente le cipolle e cuoci per altri 2 minuti prima di servire.",
    ],
    tip: "Lo sgombro ha un sapore intenso: questa ricetta si sposa bene con del pane di segale.",
    art: "/graphics/onion.jpg",
    baseServings: 2,
  },
  {
    id: "merluzzo-livornese",
    title: "Filetti di merluzzo alla livornese con pomodoro e olive",
    description:
      "Un classico della cucina di mare casalinga, ideale per trasformare i filetti di merluzzo in un piatto goloso.",
    minutes: 20,
    diet: "omnivore",
    tags: ["merluzzo", "pomodori", "olive", "capperi"],
    ingredients: [
      "400 g di filetti di merluzzo (freschi o surgelati scongelati)",
      "200 g di polpa o passata di pomodoro",
      "10 olive verdi o nere snocciolate",
      "1 cucchiaio di capperi sotto sale dissalati",
      "1 spicchio d'aglio",
      "2 cucchiai di olio extravergine d'oliva",
      "sale e prezzemolo",
    ],
    steps: [
      "In una padella scalda l'olio con l'aglio schiacciato, poi aggiungi la polpa di pomodoro, le olive tagliate a rondelle e i capperi. Cuoci il sugo per 5 minuti.",
      "Adagia i filetti di merluzzo nel sugo di pomodoro.",
      "Copri con il coperchio e cuoci a fuoco medio per circa 10 minuti, girando i filetti a metà cottura con molta delicatezza.",
      "Regola di sale se necessario e completa con il prezzemolo tritato fresco.",
    ],
    tip: "Puoi usare questa base di sugo ricca anche per condire un primo piatto di pasta espresso.",
    art: "/graphics/tomato.jpg",
    baseServings: 2,
  },
  {
    id: "tonno-sesamo",
    title: "Tonno fresco scottato in crosta di sesamo",
    description:
      "Una preparazione raffinata ma semplicissima, che richiede pochissimi minuti per mantenere il tonno succoso.",
    minutes: 10,
    diet: "omnivore",
    tags: ["tonno", "sesamo", "limone"],
    ingredients: [
      "2 tranci di tonno fresco (circa 150 g l'uno)",
      "2 cucchiai di semi di sesamo bianco",
      "2 cucchiai di semi di sesamo nero",
      "1 cucchiaio di olio extravergine d'oliva",
      "sale in fiocchi o fine",
      "1 limone",
    ],
    steps: [
      "Mescola i semi di sesamo bianco e nero in un piatto piano.",
      "Passa i tranci di tonno nel mix di sesamo facendolo aderire perfettamente su tutti i lati premendo leggermente con le mani.",
      "Scalda una padella antiaderente con un filo d'olio a fiamma alta fino a farla fumare.",
      "Scotta il tonno per esattamente 1 minuto e mezzo per lato. L'interno deve rimanere rosa. Taglia a fette spesse e servi con sale e limone.",
    ],
    tip: "Assicurati che la padella sia caldissima prima di appoggiare il tonno per creare subito la crosticina senza stracuocere il cuore del pesce.",
    art: "/graphics/lemon.jpg",
    baseServings: 2,
  },
];
