import type { Recipe } from "./types";

type BookRecipe = Omit<Recipe, "missing" | "servings"> & {
  tags: string[];
  baseServings: number;
};

export const RECIPES_MEAT: BookRecipe[] = [
  {
    id: "pollo-limone",
    title: "Pollo al limone in padella",
    description:
      "Petto di pollo dorato, deglassato con limone e un filo di brodo: piatto leggero, acidulo e succoso. Pronto in venti minuti, perfetto con un contorno di verdure del frigo.",
    minutes: 20,
    diet: "omnivore",
    tags: ["pollo", "limone", "aglio"],
    ingredients: [
      "400 g di petto di pollo",
      "1 limone (succo e scorza)",
      "1 spicchio d'aglio",
      "2 cucchiai di olio extravergine",
      "sale, pepe e prezzemolo",
    ],
    steps: [
      "Taglia il pollo a fette o striscioline. Sala e pepa.",
      "Scalda l'olio in padella, aggiungi l'aglio e fai dorare il pollo 3–4 minuti per lato.",
      "Sfumalo con il succo di limone, aggiungi la scorza e un filo d'acqua se serve.",
      "Cuoci ancora 2 minuti a fuoco medio. Completa con prezzemolo.",
      "Servi subito, eventualmente con riso o verdure.",
    ],
    tip: "Non cuocere troppo il petto: appena non è più rosato al centro, spegni. Continua a cuocere col calore residuo.",
    art: "/graphics/lemon.jpg",
    baseServings: 2,
  },
  {
    id: "pollo-funghi",
    title: "Pollo ai funghi",
    description:
      "Pollo e funghi rosolati insieme, legati da una leggera cremina: piatto unico saporito e confortante. Ideale quando hai sia pollo che funghi in frigo.",
    minutes: 30,
    diet: "omnivore",
    tags: ["pollo", "funghi", "aglio", "panna"],
    ingredients: [
      "400 g di pollo a pezzi o striscioline",
      "300 g di funghi",
      "1 spicchio d'aglio",
      "100 ml di panna o latte",
      "2 cucchiai di olio",
      "sale, pepe e prezzemolo",
    ],
    steps: [
      "Rosola il pollo nell'olio a fuoco medio-alto finché dorato. Toglilo e tieni da parte.",
      "Nella stessa padella fai rosolare i funghi con l'aglio 6–7 minuti.",
      "Rimetti il pollo, aggiungi la panna, sala e lascia restringere 5 minuti.",
      "Pepa, completa con prezzemolo e servi.",
    ],
    tip: "Se usi latte invece della panna, lega con un cucchiaino di farina sciolta a freddo.",
    art: "/graphics/mushrooms.jpg",
    baseServings: 2,
  },
  {
    id: "pollo-peperoni",
    title: "Pollo e peperoni in padella",
    description:
      "Striscioline di pollo e peperoni colorati cotti insieme: dolcezza dei peperoni, sapore del pollo e un filo di aceto per bilanciare. Piatto unico colorato e bilanciato.",
    minutes: 30,
    diet: "omnivore",
    tags: ["pollo", "peperoni", "cipolla"],
    ingredients: [
      "400 g di petto di pollo a striscioline",
      "2 peperoni",
      "1 cipolla",
      "2 cucchiai di olio",
      "sale, pepe e un filo di aceto o limone",
    ],
    steps: [
      "Taglia peperoni e cipolla a strisce. Rosola il pollo nell'olio, poi toglilo.",
      "Nella stessa padella stufa cipolla e peperoni 12–15 minuti a fuoco medio, coperti.",
      "Rimetti il pollo, sala, pepa e cuoci ancora 5 minuti.",
      "Sfumalo con un filo di aceto o limone a fine cottura. Servi.",
    ],
    tip: "I peperoni devono diventare morbidi e leggermente caramellati: non avere fretta.",
    art: "/graphics/pepper.jpg",
    baseServings: 2,
  },
  {
    id: "pollo-yogurt",
    title: "Pollo marinato allo yogurt",
    description:
      "Petto di pollo marinato in yogurt, limone e spezie, poi cotto in padella: resta morbido e succoso. Una marinatura veloce che trasforma un taglio magro.",
    minutes: 25,
    diet: "omnivore",
    tags: ["pollo", "yogurt", "limone"],
    ingredients: [
      "400 g di petto di pollo",
      "150 g di yogurt bianco",
      "succo di 1/2 limone",
      "1 spicchio d'aglio",
      "sale, pepe e paprika (opzionale)",
      "1 cucchiaio di olio",
    ],
    steps: [
      "Mescola yogurt, limone, aglio grattugiato, sale e pepe. Immergi il pollo e lascia marinare almeno 15 minuti (o di più).",
      "Scalda l'olio in padella. Scola il pollo dall'eccesso di marinatura e cuocilo 4–5 minuti per lato.",
      "A fine cottura puoi aggiungere un cucchiaio di marinatura per legare.",
      "Servi con insalata o riso.",
    ],
    tip: "Lo yogurt intenerisce le fibre: anche 15 minuti fanno differenza. Non superare i 30 minuti a temperatura ambiente.",
    art: "/graphics/lemon.jpg",
    baseServings: 2,
  },
  {
    id: "polpette-sugo",
    title: "Polpette al sugo",
    description:
      "Polpette morbide di carne macinata, passate in padella e finite nel sugo di pomodoro. Piatto della nonna, confortante e perfetto con il pane per fare la scarpetta.",
    minutes: 35,
    diet: "omnivore",
    tags: ["carne macinata", "pomodori", "uova", "parmigiano"],
    ingredients: [
      "400 g di carne macinata",
      "1 uovo",
      "30 g di parmigiano",
      "pangrattato q.b.",
      "400 g di passata di pomodoro",
      "1/2 cipolla",
      "olio, sale e pepe",
    ],
    steps: [
      "Mescola carne, uovo, parmigiano, un po' di pangrattato, sale e pepe. Forma polpette della grandezza di una noce.",
      "Rosolale in olio abbondante finché dorate. Toglie e tieni da parte.",
      "Nella stessa padella soffriggi la cipolla, aggiungi la passata e lascia sobbollire 10 minuti.",
      "Rimetti le polpette nel sugo e cuoci altri 10 minuti a fuoco basso.",
      "Servi con pane o pasta.",
    ],
    tip: "Non pressare troppo le polpette: devono restare morbide. Se si sbriciolano, aggiungi un filo di pangrattato.",
    art: "/graphics/tomato.jpg",
    baseServings: 2,
  },
  {
    id: "ragu-veloce",
    title: "Ragù veloce in padella",
    description:
      "Carne macinata, cipolla, pomodoro e un filo di vino: ragù in mezz'ora invece che in tre ore. Non è il ragù della domenica, ma è buono, saporito e salva-cena.",
    minutes: 30,
    diet: "omnivore",
    tags: ["carne macinata", "pomodori", "cipolla", "vino"],
    ingredients: [
      "400 g di carne macinata",
      "1 cipolla",
      "400 g di passata di pomodoro",
      "1/2 bicchiere di vino rosso (opzionale)",
      "2 cucchiai di olio",
      "sale, pepe e alloro",
    ],
    steps: [
      "Soffriggi la cipolla tritata nell'olio. Aggiungi la carne e rosolala bene sbriciolandola.",
      "Sfumala con il vino e lascia evaporare. Aggiungi la passata, sale e alloro.",
      "Lascia sobbollire 20 minuti a fuoco medio-basso, mescolando ogni tanto.",
      "Regola di sale e pepe. Usa per condire pasta o come base per lasagne veloci.",
    ],
    tip: "Rosola bene la carne prima di aggiungere il pomodoro: il sapore di tostatura fa la differenza.",
    art: "/graphics/tomato.jpg",
    baseServings: 2,
  },
  {
    id: "salsiccia-peperoni",
    title: "Salsiccia e peperoni",
    description:
      "Salsicce intere o a pezzi e peperoni stufati insieme: piatto rustico, dolce e saporito. Ideale con pane casereccio o polenta. Un classico delle cucine del Centro-Sud.",
    minutes: 35,
    diet: "omnivore",
    tags: ["salsiccia", "peperoni", "cipolla"],
    ingredients: [
      "4 salsicce",
      "3 peperoni",
      "1 cipolla",
      "2 cucchiai di olio",
      "sale e origano",
    ],
    steps: [
      "Rosola le salsicce intere o a pezzi in padella finché dorate. Toglie e tieni da parte.",
      "Nella stessa padella stufa cipolla e peperoni a strisce 15 minuti.",
      "Rimetti le salsicce, copri e cuoci altri 10 minuti a fuoco medio.",
      "Sala, aggiungi origano e servi caldo.",
    ],
    tip: "Se le salsicce rilasciano tanto grasso, eliminane un po' prima di aggiungere i peperoni.",
    art: "/graphics/pepper.jpg",
    baseServings: 2,
  },
  {
    id: "scaloppine-limone",
    title: "Scaloppine al limone",
    description:
      "Fettine di vitello o pollo infarinate, dorate e deglassate al limone: piatto elegante e veloce della tradizione. Salsa leggera, acidula e lucida.",
    minutes: 20,
    diet: "omnivore",
    tags: ["pollo", "limone", "burro"],
    ingredients: [
      "400 g di fettine di pollo o vitello",
      "farina q.b.",
      "1 limone",
      "30 g di burro",
      "1 cucchiaio di olio",
      "sale e prezzemolo",
    ],
    steps: [
      "Infarina le fettine scuotendo l'eccesso. Scalda olio e metà burro in padella.",
      "Cuoci le scaloppine 2 minuti per lato a fuoco medio-alto. Sala e togli.",
      "Nella stessa padella aggiungi il resto del burro e il succo di limone. Deglassa.",
      "Rimetti le scaloppine per 30 secondi. Completa con prezzemolo e servi.",
    ],
    tip: "Non sovraffollare la padella: cuoci in due turni se serve, altrimenti non dorano.",
    art: "/graphics/lemon.jpg",
    baseServings: 2,
  },
  {
    id: "hamburger-padella",
    title: "Hamburger in padella",
    description:
      "Hamburger di carne macinata cotti in padella, succosi e dorati. Semplici, buoni e pronti in dieci minuti. Servili con insalata, pomodoro e un filone di pane.",
    minutes: 15,
    diet: "omnivore",
    tags: ["carne macinata", "cipolla"],
    ingredients: [
      "400 g di carne macinata",
      "sale e pepe",
      "1 cucchiaio di olio",
      "pane per hamburger, insalata, pomodoro (per servire)",
    ],
    steps: [
      "Sala e pepa la carne, forma due hamburger alti senza compattarli troppo.",
      "Scalda la padella con l'olio a fuoco medio-alto. Cuoci 3–4 minuti per lato.",
      "Non premere con la spatola: spremeresti i succhi.",
      "Servi nel pane con condimenti a piacere.",
    ],
    tip: "Per un hamburger più saporito, mescola un filo di cipolla grattugiata nella carne prima di formare i dischi.",
    art: "/graphics/onion.jpg",
    baseServings: 2,
  },
  {
    id: "pollo-forno",
    title: "Pollo al forno alle erbe",
    description:
      "Fusi o sovracosce di pollo cotti in forno con limone, aglio e erbe: pelle croccante, carne succosa. Poco lavoro, grande risultato. Ideale per preparare in anticipo.",
    minutes: 45,
    diet: "omnivore",
    tags: ["pollo", "limone", "aglio", "erbe"],
    ingredients: [
      "4 fusi o sovracosce di pollo",
      "1 limone",
      "3 spicchi d'aglio",
      "olio extravergine",
      "rosmarino o timo, sale e pepe",
    ],
    steps: [
      "Preriscalda il forno a 200°C. Disponi il pollo in una teglia, condisci con olio, sale, pepe, aglio e erbe.",
      "Aggiungi fette di limone e un filo d'acqua sul fondo.",
      "Cuoci 40–45 minuti, girando a metà cottura, finché la pelle è dorata e il succo esce chiaro.",
      "Fai riposare 5 minuti prima di servire.",
    ],
    tip: "Per una pelle più croccante, asciuga bene il pollo con carta assorbente prima di condirlo.",
    art: "/graphics/lemon.jpg",
    baseServings: 2,
  },
];
